PASER_TU_RREP_ACK Class Reference
PASER_TU_RREP_ACK Class Reference
Packet Structure
Class implements PASER_TU_RREP_ACK messages.
#include <PASER_TU_RREP_ACK.h>
Public Member Functions
PASER_TU_RREP_ACK (const PASER_TU_RREP_ACK &m)
PASER_TU_RREP_ACK (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
~PASER_TU_RREP_ACK ()
PASER_TU_RREP_ACK & operator= (const PASER_TU_RREP_ACK &m)
virtual PASER_TU_RREP_ACK * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
u_int32_t keyNr
Current number of GTK.
uint8_t * secret
Secret of forwarding node.
std::list< uint8_t * > auth
Authentication path of forwarding node.
uint8_t * hash
Hash of the packet.
Detailed Description
Class implements PASER_TU_RREP_ACK messages.
Implementation of PASER_TU_RREPACK classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 35 of file PASER_TU_RREP_ACK.h.
Constructor & Destructor Documentation
PASER_TU_RREP_ACK::PASER_TU_RREP_ACK (const PASER_TU_RREP_ACK & m)
Constructor of PASER_TU_RREPACK packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 31 of file PASER_TU_RREP_ACK.cc.
References operator=(), and PASER_TU_RREP_ACK().
Referenced by PASER_TU_RREP_ACK().
PASER_TU_RREP_ACK::PASER_TU_RREP_ACK (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
Constructor of PASER_TU_RREPACK packet that creates a new packet.
Parameters:
src ip address of sending node
dest ip address of querying node
seqNr sequence number of sending node
Definition at line 42 of file PASER_TU_RREP_ACK.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_TU_RREP_ACK(), PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_TU_RREP_ACK::~PASER_TU_RREP_ACK ()
Destructor
Definition at line 196 of file PASER_TU_RREP_ACK.cc.
References auth, hash, and secret.
Member Function Documentation
std::string PASER_TU_RREP_ACK::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 248 of file PASER_TU_RREP_ACK.cc.
References auth, PASER_MSG::destAddress_var, hash, keyNr, PASER_SECRET_HASH_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
virtual PASER_TU_RREP_ACK* PASER_TU_RREP_ACK::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 51 of file PASER_TU_RREP_ACK.h.
uint8_t * PASER_TU_RREP_ACK::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 348 of file PASER_TU_RREP_ACK.cc.
References hash, PASER_SECRET_HASH_LEN, and toByteArray().
PASER_TU_RREP_ACK & PASER_TU_RREP_ACK::operator= (const PASER_TU_RREP_ACK & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 213 of file PASER_TU_RREP_ACK.cc.
References auth, PASER_MSG::destAddress_var, hash, keyNr, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by PASER_TU_RREP_ACK().
uint8_t * PASER_TU_RREP_ACK::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 292 of file PASER_TU_RREP_ACK.cc.
References auth, PASER_MSG::destAddress_var, keyNr, PASER_SECRET_LEN, secret, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
Referenced by PASER_crypto_hash::checkHmacTURREPACK(), PASER_crypto_hash::computeHmacTURREPACK(), and getCompleteByteArray().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_TU_RREP_ACK.h
src/PASER/packet_structure/PASER_TU_RREP_ACK.cc