PASER_scheduler Class Reference
PASER_scheduler Class Reference
Scheduler
Class provides functions for working with PASERs scheduler.
#include <PASER_scheduler.h>
Public Member Functions
void scheduler ()
Detailed Description
Class provides functions for working with PASERs scheduler.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 33 of file PASER_scheduler.h.
Member Function Documentation
void PASER_scheduler::scheduler ()
Main scheduler event loop.
Definition at line 44 of file PASER_scheduler.cc.
References PASER_socket::closeSSLSocket(), DEV_NR, PASER_global::getPASERtimeofday(), PASER_packet_processing::handleLowerMsg(), PASER_socket::readDataFromKernel(), PASER_socket::readDataFromNetwork(), PASER_socket::readDataFromSSL(), PASER_timer_packet::timeout, PASER_timer_queue::timer_get_next_timer(), and PASER_global::UpdateTime().
The documentation for this class was generated from the following files:
src/PASER/scheduler/PASER_scheduler.h
src/PASER/scheduler/PASER_scheduler.cc