PASER_GTKREP Class Reference
PASER_GTKREP Class Reference
Packet Structure
Class implements GTK-response messages.
#include <PASER_GTKREP.h>
Public Member Functions
virtual PASER_GTKREP * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
lv_block gtk
GTK.
int nonce
Nonce of registered nodes.
lv_block crl
CRL.
lv_block kdc_cert
Certificate of KDC.
int kdc_key_nr
GTK number.
lv_block sign_key
Signature of RESET message.
lv_block sign_kdc_block
Signature of KDC Block.
Detailed Description
Class implements GTK-response messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 31 of file PASER_GTKREP.h.
Member Function Documentation
std::string PASER_GTKREP::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Implements PASER_MSG.
Definition at line 338 of file PASER_GTKREP.cc.
References crl, gtk, kdc_cert, kdc_key_nr, nonce, sign_kdc_block, sign_key, PASER_MSG::srcAddress_var, and PASER_MSG::type.
virtual PASER_GTKREP* PASER_GTKREP::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 53 of file PASER_GTKREP.h.
uint8_t * PASER_GTKREP::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 482 of file PASER_GTKREP.cc.
References toByteArray().
uint8_t * PASER_GTKREP::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 395 of file PASER_GTKREP.cc.
References crl, gtk, kdc_cert, kdc_key_nr, nonce, sign_kdc_block, sign_key, and PASER_MSG::srcAddress_var.
Referenced by PASER_crypto_sign::checkSignGTKResponse(), getCompleteByteArray(), and KDC_crypto_sign::signResponse().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_GTKREP.h
src/PASER/packet_structure/PASER_GTKREP.cc