PASER_route_maintenance Class Reference
PASER_route_maintenance Class Reference
Route Maintenance
Class provides functions for working with PASER timers and Link Layer Feedback.
#include <PASER_route_maintenance.h>
Public Member Functions
void handleSelfMsg ()
void packetFailed (struct in_addr src, struct in_addr dest, bool sendRERR)
Detailed Description
Class provides functions for working with PASER timers and Link Layer Feedback.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 33 of file PASER_route_maintenance.h.
Member Function Documentation
void PASER_route_maintenance::handleSelfMsg ()
These are timeout functions which are called when timers expire. Get the next timer and checks the type to the necessary conversions and call the corresponding functions to handle the information.
Definition at line 32 of file PASER_route_maintenance.cc.
References PASER_global::getPASERtimeofday(), PASER_timer_packet::handler, PASER_timer_packet::timeout, and PASER_timer_queue::timer_get_next_timer().
void PASER_route_maintenance::packetFailed (struct in_addr src, struct in_addr dest, bool sendRERR)
Process a link layer feedback. Delete unreachable routes from routing and neighbor tables.
Parameters:
src not used
dest IP address to which the route has been broken
sendRERR should the RERR message be send
Definition at line 450 of file PASER_route_maintenance.cc.
References PASER_routing_table::deleteFromKernelRoutingTableNodesWithNextHopAddr(), PASER_routing_entry::dest_addr, PASER_neighbor_table::findNeigh(), PASER_routing_table::getListWithNextHop(), PASER_global::getPASERtimeofday(), PASER_neighbor_entry::neighbor_addr, PASER_routing_entry::nxthop_addr, and PASER_routing_entry::seqnum.
The documentation for this class was generated from the following files:
src/PASER/route_maintenance/PASER_route_maintenance.h
src/PASER/route_maintenance/PASER_route_maintenance.cc