PASER_socket Class Reference
PASER_socket Class Reference
Socket
Class provides an interface to kernel space and to network device/wireless card.
#include <PASER_socket.h>
Public Member Functions
void sendUDPToIPOverNetwork (uint8_t *s, int length, const in_addr destAddr, int destPort, network_device *netDevice)
void sendUDPToIPOverSSL (uint8_t *s, int length, const in_addr destAddr, int destPort, network_device *netDevice)
lv_block readDataFromNetwork (network_device *netDevice)
lv_block readDataFromSSL (int sock)
lv_block readDataFromKernel ()
lv_block getLastPacket ()
void closeSSLSocket (int sock)
Detailed Description
Class provides an interface to kernel space and to network device/wireless card.
The main PASER class.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 51 of file PASER_socket.h.
Member Function Documentation
void PASER_socket::closeSSLSocket (int sock)
Close SSL Socket on given socket
Parameters:
sock Socket FD
Definition at line 719 of file PASER_socket.cc.
Referenced by PASER_scheduler::scheduler().
lv_block PASER_socket::getLastPacket () [inline]
Get last sent packet.
Returns:
last sent packet.
Definition at line 111 of file PASER_socket.h.
lv_block PASER_socket::readDataFromKernel ()
Read a data from kernel
Returns:
on success, lv_block of reading data.
Definition at line 346 of file PASER_socket.cc.
Referenced by PASER_scheduler::scheduler().
lv_block PASER_socket::readDataFromNetwork (network_device * netDevice)
Read a data from socket.
Parameters:
b length of reading data. Will be set after function call.
netDevice Pointer to network device on which data is available.
Returns:
on success, Pointer to Buffer. On Error NULL.
Definition at line 666 of file PASER_socket.cc.
Referenced by PASER_scheduler::scheduler().
lv_block PASER_socket::readDataFromSSL (int sock)
Read a data from socket.
Parameters:
sock File descriptor of socket on which data is available.
Returns:
on success, lv_block of Buffer.
Definition at line 687 of file PASER_socket.cc.
Referenced by PASER_scheduler::scheduler().
void PASER_socket::sendUDPToIPOverNetwork (uint8_t * s, int length, const in_addr destAddr, int destPort, network_device * netDevice)
Send PASER packet over PASER network.
Definition at line 522 of file PASER_socket.cc.
References PASER_BROADCAST, and PASER_IPTTL.
Referenced by PASER_packet_sender::forward_ub_rreq(), and PASER_packet_sender::send_ub_rreq().
void PASER_socket::sendUDPToIPOverSSL (uint8_t * s, int length, const in_addr destAddr, int destPort, network_device * netDevice)
Send PASER packet over SSL connection.
Definition at line 632 of file PASER_socket.cc.
Referenced by PASER_packet_sender::sendKDCRequest().
The documentation for this class was generated from the following files:
src/PASER/paser_socket/PASER_socket.h
src/PASER/paser_socket/PASER_socket.cc