PASER_crypto_hash Class Reference
PASER_crypto_hash Class Reference
Cryptography
Class provides functions to compute and check the hash value of PASER messages.
#include <PASER_crypto_hash.h>
Public Member Functions
PASER_crypto_hash (PASER_global *paser_global)
int computeHmacTURREQ (PASER_TU_RREQ *packet, lv_block GTK)
int checkHmacTURREQ (PASER_TU_RREQ *packet, lv_block GTK)
int computeHmacTURREP (PASER_TU_RREP *packet, lv_block GTK)
int checkHmacTURREP (PASER_TU_RREP *packet, lv_block GTK)
int computeHmacTURREPACK (PASER_TU_RREP_ACK *packet, lv_block GTK)
int checkHmacTURREPACK (PASER_TU_RREP_ACK *packet, lv_block GTK)
int computeHmacRERR (PASER_TB_RERR *packet, lv_block GTK)
int checkHmacRERR (PASER_TB_RERR *packet, lv_block GTK)
int computeHmacHELLO (PASER_TB_HELLO *packet, lv_block GTK)
int checkHmacHELLO (PASER_TB_HELLO *packet, lv_block GTK)
Detailed Description
Class provides functions to compute and check the hash value of PASER messages.
Implementation of PASER_crypto_hash classes.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 42 of file PASER_crypto_hash.h.
Constructor & Destructor Documentation
PASER_crypto_hash::PASER_crypto_hash (PASER_global * paser_global)
Constructor of PASER_crypto_hash Object.
Parameters:
paser_global Pointer to global object
Returns:
nada
Definition at line 45 of file PASER_crypto_hash.cc.
Member Function Documentation
int PASER_crypto_hash::checkHmacHELLO (PASER_TB_HELLO * packet, lv_block GTK)
check a hash value from PASER_TB_HELLO packet
Parameters:
packet pointer to the PASER_TB_HELLO packet which hash will be checked
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 258 of file PASER_crypto_hash.cc.
References PASER_TB_HELLO::hash, and PASER_TB_HELLO::toByteArray().
int PASER_crypto_hash::checkHmacRERR (PASER_TB_RERR * packet, lv_block GTK)
check a hash value from PASER_TB_RERR packet
Parameters:
packet pointer to the PASER_TB_RERR packet which hash will be checked
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 212 of file PASER_crypto_hash.cc.
References PASER_TB_RERR::hash, and PASER_TB_RERR::toByteArray().
int PASER_crypto_hash::checkHmacTURREP (PASER_TU_RREP * packet, lv_block GTK)
check a hash value from PASER_TU_RREP packet
Parameters:
packet pointer to the PASER_TU_RREP packet which hash will be checked
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 120 of file PASER_crypto_hash.cc.
References PASER_TU_RREP::hash, and PASER_TU_RREP::toByteArray().
int PASER_crypto_hash::checkHmacTURREPACK (PASER_TU_RREP_ACK * packet, lv_block GTK)
check a hash value from PASER_TU_RREPACK packet
Parameters:
packet pointer to the PASER_TU_RREPACK packet which hash will be checked
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 166 of file PASER_crypto_hash.cc.
References PASER_TU_RREP_ACK::hash, and PASER_TU_RREP_ACK::toByteArray().
int PASER_crypto_hash::checkHmacTURREQ (PASER_TU_RREQ * packet, lv_block GTK)
check a hash value from PASER_TU_RREQ packet
Parameters:
packet pointer to the PASER_TU_RREQ packet which hash will be checked
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 74 of file PASER_crypto_hash.cc.
References PASER_TU_RREQ::hash, and PASER_TU_RREQ::toByteArray().
int PASER_crypto_hash::computeHmacHELLO (PASER_TB_HELLO * packet, lv_block GTK)
Compute a hash value from PASER_TB_HELLO packet and GTK and write the hash value to packet
Parameters:
packet pointer to the PASER_TB_HELLO packet which will be hashed
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 237 of file PASER_crypto_hash.cc.
References PASER_TB_HELLO::hash, and PASER_TB_HELLO::toByteArray().
int PASER_crypto_hash::computeHmacRERR (PASER_TB_RERR * packet, lv_block GTK)
Compute a hash value from PASER_TB_RERR packet and GTK and write the hash value to packet
Parameters:
packet pointer to the PASER_TB_RERR packet which will be hashed
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 191 of file PASER_crypto_hash.cc.
References PASER_TB_RERR::hash, and PASER_TB_RERR::toByteArray().
int PASER_crypto_hash::computeHmacTURREP (PASER_TU_RREP * packet, lv_block GTK)
Compute a hash value from PASER_TU_RREP packet and GTK and write the hash value to packet
Parameters:
packet pointer to the PASER_TU_RREP packet which will be hashed
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 99 of file PASER_crypto_hash.cc.
References PASER_TU_RREP::hash, and PASER_TU_RREP::toByteArray().
int PASER_crypto_hash::computeHmacTURREPACK (PASER_TU_RREP_ACK * packet, lv_block GTK)
Compute a hash value from PASER_TU_RREPACK packet and GTK and write the hash value to packet
Parameters:
packet pointer to the PASER_TU_RREPACK packet which will be hashed
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 145 of file PASER_crypto_hash.cc.
References PASER_TU_RREP_ACK::hash, and PASER_TU_RREP_ACK::toByteArray().
int PASER_crypto_hash::computeHmacTURREQ (PASER_TU_RREQ * packet, lv_block GTK)
Compute a hash value from PASER_TU_RREQ packet and GTK and write the hash value to packet
Parameters:
packet pointer to the PASER_TU_RREQ packet which will be hashed
GTK current GTK
Returns:
1 on successful or 0 on error
Definition at line 49 of file PASER_crypto_hash.cc.
References PASER_TU_RREQ::hash, and PASER_TU_RREQ::toByteArray().
The documentation for this class was generated from the following files:
src/PASER/crypto/PASER_crypto_hash.h
src/PASER/crypto/PASER_crypto_hash.cc