PASER_TU_RREP Class Reference
PASER_TU_RREP Class Reference
Packet Structure
Class implements PASER_TU_RREP messages.
#include <PASER_TU_RREP.h>
Public Member Functions
PASER_TU_RREP (const PASER_TU_RREP &m)
PASER_TU_RREP (struct in_addr src, struct in_addr dest, int seqNr)
~PASER_TU_RREP ()
PASER_TU_RREP & operator= (const PASER_TU_RREP &m)
virtual PASER_TU_RREP * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
u_int32_t keyNr
/ Current number of GTK
uint8_t searchGW
/ search for the gateway
uint8_t GFlag
/ Gateway flag
std::list< address_list > AddressRangeList
/ Route list from querying node to forwarding node
uint8_t metricBetweenQueryingAndForw
Metric for the route between querying node and forwarding node.
uint8_t metricBetweenDestAndForw
Metric for the route between destination node and forwarding node.
kdc_block kdc_data
KDC Block.
geo_pos geoDestination
Geographical position of destination node.
geo_pos geoForwarding
Geographical position of forwarding node.
uint8_t * secret
Secret of forwarding node.
std::list< uint8_t * > auth
Authentication path of forwarding node.
uint8_t * hash
Hash of the packet.
Detailed Description
Class implements PASER_TU_RREP messages.
Implementation of PASER_TU_RREP classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 37 of file PASER_TU_RREP.h.
Constructor & Destructor Documentation
PASER_TU_RREP::PASER_TU_RREP (const PASER_TU_RREP & m)
Constructor of PASER_TU_RREP packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 32 of file PASER_TU_RREP.cc.
References operator=(), and PASER_TU_RREP().
Referenced by PASER_TU_RREP().
PASER_TU_RREP::PASER_TU_RREP (struct in_addr src, struct in_addr dest, int seqNr)
Constructor of PASER_TU_RREP packet that creates a new packet.
Parameters:
src ip address of sending node
dest ip address of querying node
seqNr sequence number of sending node
Definition at line 43 of file PASER_TU_RREP.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_TU_RREP(), searchGW, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_TU_RREP::~PASER_TU_RREP ()
Destructor
Definition at line 606 of file PASER_TU_RREP.cc.
References auth, GFlag, hash, kdc_data, and secret.
Member Function Documentation
std::string PASER_TU_RREP::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 711 of file PASER_TU_RREP.cc.
References AddressRangeList, auth, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, hash, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, PASER_SECRET_HASH_LEN, PASER_SECRET_LEN, searchGW, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
virtual PASER_TU_RREP* PASER_TU_RREP::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 66 of file PASER_TU_RREP.h.
uint8_t * PASER_TU_RREP::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 1009 of file PASER_TU_RREP.cc.
References hash, PASER_SECRET_HASH_LEN, and toByteArray().
PASER_TU_RREP & PASER_TU_RREP::operator= (const PASER_TU_RREP & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 631 of file PASER_TU_RREP.cc.
References AddressRangeList, auth, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, hash, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, PASER_SECRET_LEN, searchGW, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by PASER_TU_RREP().
uint8_t * PASER_TU_RREP::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 822 of file PASER_TU_RREP.cc.
References AddressRangeList, auth, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, PASER_SECRET_LEN, searchGW, secret, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
Referenced by PASER_crypto_hash::checkHmacTURREP(), PASER_crypto_hash::computeHmacTURREP(), and getCompleteByteArray().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_TU_RREP.h
src/PASER/packet_structure/PASER_TU_RREP.cc