PASER_GTKREQ Class Reference
PASER_GTKREQ Class Reference
Packet Structure
Class implements GTK-request messages.
#include <PASER_GTKREQ.h>
Public Member Functions
virtual PASER_GTKREQ * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Static Public Member Functions
static PASER_GTKREQ * create (uint8_t *packet, u_int32_t l)
Public Attributes
lv_block cert
Certificate of registered nodes.
int nonce
Nonce of registered nodes.
Detailed Description
Class implements GTK-request messages.
The Class provides functions for GTK-requests
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 34 of file PASER_GTKREQ.h.
Member Function Documentation
PASER_GTKREQ * PASER_GTKREQ::create (uint8_t * packet, u_int32_t l) [static]
Get a packet object from incoming data
Parameters:
packet Pointer to incoming data char array
l Length of the char array
Returns:
true if packet is valid. Else return false.
Definition at line 39 of file PASER_GTKREQ.cc.
References cert, nonce, PASER_MSG::srcAddress_var, and PASER_MSG::type.
std::string PASER_GTKREQ::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Implements PASER_MSG.
Definition at line 158 of file PASER_GTKREQ.cc.
References cert, nonce, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by PASER_packet_sender::sendKDCRequest().
virtual PASER_GTKREQ* PASER_GTKREQ::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 59 of file PASER_GTKREQ.h.
uint8_t * PASER_GTKREQ::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 215 of file PASER_GTKREQ.cc.
References toByteArray().
Referenced by PASER_packet_sender::sendKDCRequest().
uint8_t * PASER_GTKREQ::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 176 of file PASER_GTKREQ.cc.
References cert, nonce, and PASER_MSG::srcAddress_var.
Referenced by getCompleteByteArray().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_GTKREQ.h
src/PASER/packet_structure/PASER_GTKREQ.cc