PASER_B_ROOT Class Reference
PASER_B_ROOT Class Reference
Packet Structure
Class implements PASER_B_ROOT messages.
#include <PASER_B_ROOT.h>
Public Member Functions
PASER_B_ROOT (const PASER_B_ROOT &m)
PASER_B_ROOT (struct in_addr src, u_int32_t seqNr)
virtual ~PASER_B_ROOT ()
PASER_B_ROOT & operator= (const PASER_B_ROOT &m)
virtual PASER_B_ROOT * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
long timestamp
Sending time.
lv_block cert
Certificate of sending node.
uint8_t * root
The root element of sending node.
u_int32_t initVector
IV of sending or forwarding node.
geo_pos geoQuerying
Geographical position of sending node.
lv_block sign
Signature of the packet.
Detailed Description
Class implements PASER_B_ROOT messages.
Implementation of the PASER_B_ROOT classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 38 of file PASER_B_ROOT.h.
Constructor & Destructor Documentation
PASER_B_ROOT::PASER_B_ROOT (const PASER_B_ROOT & m)
Constructor of PASER_B_ROOT packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 30 of file PASER_B_ROOT.cc.
References operator=(), and PASER_B_ROOT().
Referenced by PASER_B_ROOT().
PASER_B_ROOT::PASER_B_ROOT (struct in_addr src, u_int32_t seqNr)
Constructor of PASER_B_ROOT packet that creates a new packet.
Parameters:
src ip address of sending node
seqNr sequence number of sending node
Definition at line 40 of file PASER_B_ROOT.cc.
References cert, PASER_MSG::destAddress_var, PASER_B_ROOT(), root, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
PASER_B_ROOT::~PASER_B_ROOT () [virtual]
Destructor
Definition at line 243 of file PASER_B_ROOT.cc.
References cert, root, and sign.
Member Function Documentation
std::string PASER_B_ROOT::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 299 of file PASER_B_ROOT.cc.
References cert, geoQuerying, initVector, PASER_SECRET_HASH_LEN, root, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
virtual PASER_B_ROOT* PASER_B_ROOT::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 56 of file PASER_B_ROOT.h.
uint8_t * PASER_B_ROOT::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 400 of file PASER_B_ROOT.cc.
References sign, and toByteArray().
PASER_B_ROOT & PASER_B_ROOT::operator= (const PASER_B_ROOT & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 263 of file PASER_B_ROOT.cc.
References cert, PASER_MSG::destAddress_var, geoQuerying, initVector, PASER_SECRET_HASH_LEN, root, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
Referenced by PASER_B_ROOT().
uint8_t * PASER_B_ROOT::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 338 of file PASER_B_ROOT.cc.
References cert, geoQuerying, initVector, PASER_SECRET_HASH_LEN, root, PASER_MSG::seq, PASER_MSG::srcAddress_var, and timestamp.
Referenced by PASER_crypto_sign::checkSignB_ROOT(), getCompleteByteArray(), and PASER_crypto_sign::signB_ROOT().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_B_ROOT.h
src/PASER/packet_structure/PASER_B_ROOT.cc