GPSDATA::PASER_GPS Class Reference
GPSDATA::PASER_GPS Class Reference
GPS Reader
Class provides API to read GPS Data.
#include <PASER_gpsReader.h>
Public Member Functions
PASER_GPS (PASER_global *paser_global)
double getLatitude ()
double getLongitude ()
double getAltitude ()
void Handler (const boost::system::error_code &error, size_t bytes_transferred)
void startGPS ()
Detailed Description
Class provides API to read GPS Data.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 47 of file PASER_gpsReader.h.
Constructor & Destructor Documentation
GPSDATA::PASER_GPS::PASER_GPS (PASER_global * paser_global)
Constructor of GPS Object.
Parameters:
paser_global Pointer to global object
Returns:
nada
Definition at line 26 of file PASER_gpsReader.cpp.
Member Function Documentation
double GPSDATA::PASER_GPS::getAltitude ()
Get Altitude of the Node
Returns:
Altitude of the Node
Definition at line 50 of file PASER_gpsReader.cpp.
double GPSDATA::PASER_GPS::getLatitude ()
Get Latitude of the Node
Returns:
Latitude of the Node
Definition at line 42 of file PASER_gpsReader.cpp.
Referenced by PASER_global::getLatPos().
double GPSDATA::PASER_GPS::getLongitude ()
Get Longitude of the Node
Returns:
Longitude of the Node
Definition at line 46 of file PASER_gpsReader.cpp.
void GPSDATA::PASER_GPS::Handler (const boost::system::error_code & error, size_t bytes_transferred)
Callback function to read GPS data from serial port.
Returns:
nada
Definition at line 54 of file PASER_gpsReader.cpp.
Referenced by startGPS().
void GPSDATA::PASER_GPS::startGPS ()
Main function to initialize GPS Data and start read GPS Data from serial port. This Function must be called once at initialization of PASER.
Returns:
nada
Definition at line 82 of file PASER_gpsReader.cpp.
References Handler().
Referenced by PASER_global::PASER_global().
The documentation for this class was generated from the following files:
src/PASER/gps/PASER_gpsReader.h
src/PASER/gps/PASER_gpsReader.cpp