PASER_route_discovery Class Reference
PASER_route_discovery Class Reference
Route Discovery
Class provides functions to start a registration or route discovery.
#include <PASER_route_discovery.h>
Public Member Functions
void tryToRegister ()
void route_discovery (struct in_addr dest_addr, int isDestGW)
void processPacket (struct in_addr src_addr, struct in_addr dest_addr)
Detailed Description
Class provides functions to start a registration or route discovery.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 31 of file PASER_route_discovery.h.
Member Function Documentation
void PASER_route_discovery::processPacket (struct in_addr src_addr, struct in_addr dest_addr)
Process a data packet. If the route to the destination node is not known, then route discovery is started.
Parameters:
src_addr IP address of the source node
dest_addr IP address of the destination node
Definition at line 82 of file PASER_route_discovery.cc.
References PASER_neighbor_table::findNeigh(), PASER_global::getPASERtimeofday(), PASER_routing_entry::hopcnt, PASER_config::isAddInMyLocalAddress(), PASER_neighbor_entry::isValid, PASER_routing_entry::isValid, PASER_neighbor_entry::neighFlag, PASER_routing_entry::nxthop_addr, PASER_ALLONES_ADDRESS_MASK, route_discovery(), and PASER_blacklist::setRerrTime().
void PASER_route_discovery::route_discovery (struct in_addr dest_addr, int isDestGW)
Start route discovery. The route discovery will be started only if the route discovery is not already started.
Parameters:
dest_addr IP address of destination node or broadcast if isDestGW is set.
isDestGW is set if route to a gateway must be found.
Definition at line 42 of file PASER_route_discovery.cc.
References PASER_timer_packet::data, PASER_timer_packet::destAddr, PASER_global::getPASERtimeofday(), PASER_timer_packet::handler, PASER_UB_RREQ_WAIT_TIME, PASER_packet_sender::send_ub_rreq(), PASER_timer_packet::timeout, and PASER_timer_queue::timer_add().
Referenced by processPacket(), and tryToRegister().
void PASER_route_discovery::tryToRegister ()
Start registration. If the node is unregistered the registration will be started.
Definition at line 30 of file PASER_route_discovery.cc.
References route_discovery().
The documentation for this class was generated from the following files:
src/PASER/route_discovery/PASER_route_discovery.h
src/PASER/route_discovery/PASER_route_discovery.cc