PASER_neighbor_table Class Reference
PASER_neighbor_table Class Reference
Tables
Class provides a map of node's neighbors.
#include <PASER_neighbor_table.h>
Public Member Functions
PASER_neighbor_entry * findNeigh (struct in_addr neigh_addr)
PASER_neighbor_entry * insert (struct in_addr neigh_addr, PASER_timer_packet *deleteTimer, PASER_timer_packet *validTimer, int neighFlag, u_int8_t *root, u_int32_t IV, geo_pos position, u_int8_t *Cert, u_int32_t ifIndex)
PASER_neighbor_entry * update (PASER_neighbor_entry *entry, struct in_addr neigh_addr, PASER_timer_packet *deleteTimer, PASER_timer_packet *validTimer, int neighFlag, u_int8_t *root, u_int32_t IV, geo_pos position, u_int8_t *Cert, u_int32_t ifIndex)
void delete_entry (PASER_neighbor_entry *entry)
void updateNeighborTableAndSetTableTimeout (struct in_addr neigh, int nFlag, u_int8_t *root, int iv, geo_pos position, X509 *cert, struct timeval now, u_int32_t ifIndex)
void updateNeighborTableTimeout (struct in_addr neigh, struct timeval now)
void updateNeighborTableIVandSetValid (struct in_addr neigh, u_int32_t IV)
void updateNeighborTableIV (struct in_addr neigh, u_int32_t IV)
int checkAllCert ()
void clearTable ()
Detailed Description
Class provides a map of node's neighbors.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 42 of file PASER_neighbor_table.h.
Member Function Documentation
int PASER_neighbor_table::checkAllCert ()
The function checks whether all certificates in neighbor tables are valid. All routes, nodes and neighbors that have an invalid certificates will be deleted.
Returns:
1 if a valid Route to gateway is given. Else 0.
Definition at line 226 of file PASER_neighbor_table.cc.
References PASER_neighbor_entry::Cert, PASER_crypto_sign::checkOneCert(), PASER_routing_table::delete_entry(), delete_entry(), PASER_neighbor_entry::deleteTimer, PASER_routing_entry::deleteTimer, PASER_routing_table::getListWithNextHop(), PASER_neighbor_entry::neighbor_addr, PASER_timer_queue::timer_remove(), PASER_neighbor_entry::validTimer, and PASER_routing_entry::validTimer.
void PASER_neighbor_table::clearTable ()
Clear Neighbor table and free all allocated memory
Definition at line 311 of file PASER_neighbor_table.cc.
Referenced by PASER_global::resetPASER().
void PASER_neighbor_table::delete_entry (PASER_neighbor_entry * entry)
Delete a entry from the map.
Parameters:
entry Pointer to the entry which will be deleted.
Definition at line 99 of file PASER_neighbor_table.cc.
References PASER_neighbor_entry::neighbor_addr.
Referenced by checkAllCert().
PASER_neighbor_entry * PASER_neighbor_table::findNeigh (struct in_addr neigh_addr)
Find a routing entry given the destination address
Definition at line 40 of file PASER_neighbor_table.cc.
Referenced by PASER_routing_table::deleteFromKernelRoutingTableNodesWithNextHopAddr(), PASER_routing_table::getNeighborAddressList(), PASER_route_maintenance::packetFailed(), PASER_route_discovery::processPacket(), PASER_routing_table::updateKernelRoutingTable(), PASER_routing_table::updateNeighborFromHELLO(), updateNeighborTableAndSetTableTimeout(), updateNeighborTableIV(), updateNeighborTableIVandSetValid(), updateNeighborTableTimeout(), PASER_routing_table::updateRouteFromHELLO(), PASER_routing_table::updateRouteLifetimes(), PASER_routing_table::updateRoutingTable(), and PASER_routing_table::updateRoutingTableAndSetTableTimeout().
PASER_neighbor_entry * PASER_neighbor_table::insert (struct in_addr neigh_addr, PASER_timer_packet * deleteTimer, PASER_timer_packet * validTimer, int neighFlag, u_int8_t * root, u_int32_t IV, geo_pos position, u_int8_t * Cert, u_int32_t ifIndex)
Insert a new entry to the map
Parameters:
neigh_addr IP address of the neighbor
deleteTimer Pointer to delete Timeout
validTimer Pointer to valid Timeout
neighFlag Is neighbor trusted
root Root element of the neighbor
IV Initial vector of the neighbor
position Geo Position of the neighbor
Cert Certificate of the neighbor
ifIndex Index of the network device on with the neighbor is available
Returns:
Pointer to inserted entry
Definition at line 49 of file PASER_neighbor_table.cc.
References PASER_neighbor_entry::Cert, PASER_neighbor_entry::deleteTimer, PASER_neighbor_entry::ifIndex, PASER_neighbor_entry::isValid, PASER_neighbor_entry::IV, PASER_neighbor_entry::neighbor_addr, PASER_neighbor_entry::neighFlag, PASER_neighbor_entry::position, PASER_neighbor_entry::root, and PASER_neighbor_entry::validTimer.
Referenced by updateNeighborTableAndSetTableTimeout().
PASER_neighbor_entry * PASER_neighbor_table::update (PASER_neighbor_entry * entry, struct in_addr neigh_addr, PASER_timer_packet * deleteTimer, PASER_timer_packet * validTimer, int neighFlag, u_int8_t * root, u_int32_t IV, geo_pos position, u_int8_t * Cert, u_int32_t ifIndex)
Update a entry in the map
Parameters:
entry Pointer to the entry which will be updated.
neigh_addr IP address of the neighbor
deleteTimer Pointer to delete Timeout
validTimer Pointer to valid Timeout
neighFlag Is neighbor trusted
root Root element of the neighbor
IV Initial vector of the neighbor
position Geo Position of the neighbor
Cert Certificate of the neighbor
ifIndex Index of the network device on with the neighbor is available
Returns:
Pointer to updated entry
Definition at line 68 of file PASER_neighbor_table.cc.
References PASER_neighbor_entry::Cert, PASER_neighbor_entry::deleteTimer, PASER_neighbor_entry::ifIndex, PASER_neighbor_entry::isValid, PASER_neighbor_entry::IV, PASER_neighbor_entry::neighbor_addr, PASER_neighbor_entry::neighFlag, PASER_neighbor_entry::position, PASER_neighbor_entry::root, and PASER_neighbor_entry::validTimer.
Referenced by updateNeighborTableAndSetTableTimeout().
void PASER_neighbor_table::updateNeighborTableAndSetTableTimeout (struct in_addr neigh, int nFlag, u_int8_t * root, int iv, geo_pos position, X509 * cert, struct timeval now, u_int32_t ifIndex)
Insert or update a entry in the neighbor table. If a entry not exist then a new entry will be added to the table. The delete and valid timer of the entry will be reseted.
Parameters:
neigh IP address of the node which entry will be updated.
nFlag Is neighbor trusted
root Root element of the neighbor
iv Initial vector of the neighbor
position Geo Position of the neighbor
cert Certificate of the neighbor
now Current time
ifIndex Index of the network device on with the neighbor is available
Definition at line 115 of file PASER_neighbor_table.cc.
References PASER_timer_packet::data, PASER_neighbor_entry::deleteTimer, PASER_timer_packet::destAddr, findNeigh(), PASER_timer_packet::handler, insert(), PASER_neighbor_entry::neighFlag, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), update(), and PASER_neighbor_entry::validTimer.
void PASER_neighbor_table::updateNeighborTableIV (struct in_addr neigh, u_int32_t IV)
Update IV of the entry. If a entry not exist then a new entry will be NOT added.
Definition at line 217 of file PASER_neighbor_table.cc.
References findNeigh(), and PASER_neighbor_entry::IV.
void PASER_neighbor_table::updateNeighborTableIVandSetValid (struct in_addr neigh, u_int32_t IV)
Update IV of the entry and mark the entry as valid. If a entry not exist then a new entry will be NOT added.
Definition at line 207 of file PASER_neighbor_table.cc.
References findNeigh(), PASER_neighbor_entry::isValid, and PASER_neighbor_entry::IV.
void PASER_neighbor_table::updateNeighborTableTimeout (struct in_addr neigh, struct timeval now)
Reset the delete and valid timer of an entry. If a entry not exist then a new entry will be NOT added.
Definition at line 182 of file PASER_neighbor_table.cc.
References PASER_timer_packet::data, PASER_neighbor_entry::deleteTimer, PASER_timer_packet::destAddr, findNeigh(), PASER_timer_packet::handler, PASER_neighbor_entry::isValid, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), and PASER_neighbor_entry::validTimer.
Referenced by PASER_routing_table::updateNeighborFromHELLO().
The documentation for this class was generated from the following files:
src/PASER/tables/PASER_neighbor_table.h
src/PASER/tables/PASER_neighbor_table.cc