PASER_root Class Reference
PASER_root Class Reference
Cryptography
Class provides function to generate secrets, compute and check authentication trees.
#include <PASER_root.h>
Public Member Functions
PASER_root (PASER_global *paser_global)
bool init (int n)
bool regenerate ()
uint8_t * getRoot ()
std::list< uint8_t * > getNextSecret (int *nr, uint8_t *secret)
int getIV ()
int checkRoot (uint8_t *root, uint8_t *secret, std::list< uint8_t * > iv_list, uint32_t iv, uint32_t *newIV)
Detailed Description
Class provides function to generate secrets, compute and check authentication trees.
Implementation of PASER_root classes.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 37 of file PASER_root.h.
Constructor & Destructor Documentation
PASER_root::PASER_root (PASER_global * paser_global)
Constructor. To generate a authentication tree root_tree must be called
Definition at line 46 of file PASER_root.cc.
Member Function Documentation
int PASER_root::checkRoot (uint8_t * root, uint8_t * secret, std::list< uint8_t * > iv_list, uint32_t iv, uint32_t * newIV)
check authentication path of given secret
Parameters:
root pointer to the root element of authentication path
secret pointer to the secret of authentication path
iv_list authentication path
iv last IV of the node
newIV new IV of the node @
Returns:
1 on successful or 0 on error
Definition at line 242 of file PASER_root.cc.
References PASER_SECRET_LEN.
int PASER_root::getIV ()
Get IV
Returns:
IV
Definition at line 217 of file PASER_root.cc.
Referenced by PASER_packet_sender::forward_ub_rreq(), and PASER_packet_sender::send_ub_rreq().
std::list< uint8_t * > PASER_root::getNextSecret (int * nr, uint8_t * secret)
Get next new and fresh secret
Parameters:
nr pointer to IV which will be set after the function will be called
secret pointer to secret which will be set after the function will be called
Returns:
authentication path of current secret
Definition at line 148 of file PASER_root.cc.
References PASER_timer_packet::data, PASER_timer_packet::destAddr, PASER_global::getPASERtimeofday(), PASER_timer_packet::handler, PASER_BROADCAST, PASER_SECRET_LEN, regenerate(), PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), and PASER_timer_queue::timer_sort().
uint8_t * PASER_root::getRoot ()
Get Root element
Returns:
root element
Definition at line 142 of file PASER_root.cc.
References PASER_SECRET_HASH_LEN.
Referenced by PASER_packet_sender::forward_ub_rreq(), and PASER_packet_sender::send_ub_rreq().
bool PASER_root::init (int n)
initialize the object, generate secrets and compute authentication tree
Parameters:
n number of generated secrets 2^param
Returns:
true on successful or false on error
Definition at line 67 of file PASER_root.cc.
References regenerate().
Referenced by PASER_global::PASER_global().
bool PASER_root::regenerate ()
Generate secrets and compute authentication tree
Returns:
true on successful or false on error
Definition at line 76 of file PASER_root.cc.
References PASER_SECRET_LEN.
Referenced by getNextSecret(), and init().
The documentation for this class was generated from the following files:
src/PASER/crypto/PASER_root.h
src/PASER/crypto/PASER_root.cc