PASER_routing_table Class Reference
PASER_routing_table Class Reference
Tables
Class provides a map of node's routes.
#include <PASER_routing_table.h>
Public Member Functions
std::list< PASER_routing_entry * > getListWithNextHop (struct in_addr nextHop)
PASER_routing_entry * insert (struct in_addr dest_addr, struct in_addr nxthop_addr, PASER_timer_packet *deltimer, PASER_timer_packet *validtimer, u_int32_t seqnum, u_int8_t hopcnt, u_int8_t is_gw, std::list< address_range > AddL, u_int8_t *Cert)
PASER_routing_entry * update (PASER_routing_entry *entry, struct in_addr dest_addr, struct in_addr nxthop_addr, PASER_timer_packet *deltimer, PASER_timer_packet *validtimer, u_int32_t seqnum, u_int8_t hopcnt, u_int8_t is_gw, std::list< address_range > AddL, u_int8_t *Cert)
void delete_entry (PASER_routing_entry *entry)
PASER_routing_entry * getRouteToGw ()
PASER_routing_entry * findBestGW ()
void updateKernelRoutingTable (struct in_addr dest_addr, struct in_addr forw_addr, struct in_addr netmask, u_int32_t metric, bool del_entry, int ifIndex)
void updateRoutingTableAndSetTableTimeout (std::list< address_range > addList, struct in_addr src_addr, uint32_t seq, X509 *cert, struct in_addr nextHop, u_int8_t metric, int ifIndex, struct timeval now, u_int8_t gFlag, bool trusted)
void updateRoutingTableTimeout (struct in_addr src_addr, struct timeval now, int ifIndex)
void updateRoutingTableTimeout (struct in_addr src_addr, u_int32_t seq, struct timeval now)
void updateRoutingTable (struct timeval now, std::list< address_list > addList, struct in_addr nextHop, int ifIndex)
void deleteFromKernelRoutingTableNodesWithNextHopAddr (struct in_addr nextHop)
void updateRouteLifetimes (struct in_addr dest_addr)
void updateNeighborFromHELLO (address_list liste, u_int32_t seq, int ifIndex)
void updateRouteFromHELLO (address_list liste, int ifIndex, struct in_addr nextHop)
std::list< address_list > getNeighborAddressList (int ifNr)
void clearTable ()
Detailed Description
Class provides a map of node's routes.
Implementation of the routing table. Each valid route will be automatically added to the kernel routing table.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 48 of file PASER_routing_table.h.
Member Function Documentation
void PASER_routing_table::clearTable ()
The function checks whether all certificates in routing tables are valid. All routes, nodes and neighbors that have an invalid certificates will be deleted.
Returns:
1 if a valid Route to gateway is given. Else 0. Clear Routing table and free all allocated memory
Definition at line 766 of file PASER_routing_table.cc.
References PASER_routing_entry::AddL, and PASER_routing_entry::dest_addr.
Referenced by PASER_global::resetPASER().
void PASER_routing_table::delete_entry (PASER_routing_entry * entry)
Delete a entry from the map.
Parameters:
entry Pointer to the entry which will be deleted.
Definition at line 151 of file PASER_routing_table.cc.
References PASER_routing_entry::dest_addr.
Referenced by PASER_neighbor_table::checkAllCert().
void PASER_routing_table::deleteFromKernelRoutingTableNodesWithNextHopAddr (struct in_addr nextHop)
Delete all nodes from routing, neighbor and kernel routing tables and theirs timers which follow over the given IP address.
Parameters:
nextHop IP address
Definition at line 458 of file PASER_routing_table.cc.
References PASER_routing_entry::AddL, PASER_routing_entry::dest_addr, PASER_neighbor_table::findNeigh(), getListWithNextHop(), PASER_routing_entry::hopcnt, PASER_neighbor_entry::isValid, PASER_routing_entry::isValid, PASER_routing_entry::nxthop_addr, PASER_ALLONES_ADDRESS_MASK, PASER_timer_queue::timer_remove(), updateKernelRoutingTable(), PASER_neighbor_entry::validTimer, and PASER_routing_entry::validTimer.
Referenced by PASER_route_maintenance::packetFailed().
PASER_routing_entry * PASER_routing_table::findBestGW ()
Get the shortest Route to Gateway.
Returns:
Route to the Gateway or NULL if no Route to Gateway are given.
Definition at line 170 of file PASER_routing_table.cc.
References PASER_routing_entry::hopcnt.
Referenced by getRouteToGw().
std::list< PASER_routing_entry * > PASER_routing_table::getListWithNextHop (struct in_addr nextHop)
Get a list of all routes with a given next hop IP address
Definition at line 183 of file PASER_routing_table.cc.
References PASER_routing_entry::nxthop_addr.
Referenced by PASER_neighbor_table::checkAllCert(), deleteFromKernelRoutingTableNodesWithNextHopAddr(), and PASER_route_maintenance::packetFailed().
std::list< address_list > PASER_routing_table::getNeighborAddressList (int ifNr)
Get all neighbor nodes and set own IP address in the list to IP address of given Interface.
Definition at line 595 of file PASER_routing_table.cc.
References PASER_routing_entry::AddL, PASER_neighbor_table::findNeigh(), PASER_config::getAddL(), PASER_routing_entry::hopcnt, PASER_neighbor_entry::isValid, PASER_neighbor_entry::neighbor_addr, PASER_neighbor_entry::neighFlag, and PASER_routing_entry::nxthop_addr.
PASER_routing_entry * PASER_routing_table::getRouteToGw ()
Get the shortest Route to Gateway.
Returns:
Route to the Gateway or NULL if no Route to Gateway are given.
Definition at line 166 of file PASER_routing_table.cc.
References findBestGW().
Referenced by updateKernelRoutingTable().
PASER_routing_entry * PASER_routing_table::insert (struct in_addr dest_addr, struct in_addr nxthop_addr, PASER_timer_packet * deltimer, PASER_timer_packet * validtimer, u_int32_t seqnum, u_int8_t hopcnt, u_int8_t is_gw, std::list< address_range > AddL, u_int8_t * Cert)
Insert a new entry to the map
Definition at line 84 of file PASER_routing_table.cc.
References PASER_routing_entry::AddL, PASER_routing_entry::Cert, PASER_routing_entry::deleteTimer, PASER_routing_entry::dest_addr, PASER_routing_entry::hopcnt, PASER_routing_entry::is_gw, PASER_routing_entry::isValid, PASER_routing_entry::nxthop_addr, PASER_routing_entry::seqnum, and PASER_routing_entry::validTimer.
Referenced by updateRouteFromHELLO(), updateRoutingTable(), and updateRoutingTableAndSetTableTimeout().
PASER_routing_entry * PASER_routing_table::update (PASER_routing_entry * entry, struct in_addr dest_addr, struct in_addr nxthop_addr, PASER_timer_packet * deltimer, PASER_timer_packet * validtimer, u_int32_t seqnum, u_int8_t hopcnt, u_int8_t is_gw, std::list< address_range > AddL, u_int8_t * Cert)
Update a entry in the map
Parameters:
entry Pointer to the entry which will be updated.
dest_addr IP address of the node
nxthop_addr IP address of the next hop node
deltimer Pointer to delete Timeout
validtimer Pointer to valid Timeout
seqnum Sequence number of the node
hopcnt Metric to the node
is_gw Is the node a gateway
AddL Address range list of the node
Cert Certificate of the node
Returns:
Pointer to updated entry
Definition at line 104 of file PASER_routing_table.cc.
References PASER_routing_entry::AddL, PASER_routing_entry::Cert, PASER_routing_entry::deleteTimer, PASER_routing_entry::dest_addr, PASER_routing_entry::hopcnt, PASER_routing_entry::is_gw, PASER_routing_entry::isValid, PASER_routing_entry::nxthop_addr, PASER_routing_entry::seqnum, and PASER_routing_entry::validTimer.
Referenced by updateNeighborFromHELLO(), updateRouteFromHELLO(), updateRoutingTable(), and updateRoutingTableAndSetTableTimeout().
void PASER_routing_table::updateKernelRoutingTable (struct in_addr dest_addr, struct in_addr forw_addr, struct in_addr netmask, u_int32_t metric, bool del_entry, int ifIndex)
Add a route to kernel routing table.
Parameters:
dest_addr IP address of the destination node
forw_addr IP address of the next hop node
netmask Network mask of the destination node
metric Metric to the node
del_entry if true then the route will be deleted from the kernel table. Else a new route will be addes to the kernel table.
ifIndex Interface over which the node is reachable.
Definition at line 194 of file PASER_routing_table.cc.
References DEV_NR, PASER_neighbor_table::findNeigh(), getRouteToGw(), PASER_routing_entry::hopcnt, PASER_neighbor_entry::ifIndex, PASER_routing_entry::is_gw, PASER_neighbor_entry::isValid, PASER_neighbor_entry::neighbor_addr, PASER_neighbor_entry::neighFlag, and PASER_routing_entry::nxthop_addr.
Referenced by deleteFromKernelRoutingTableNodesWithNextHopAddr(), updateNeighborFromHELLO(), updateRouteFromHELLO(), updateRoutingTable(), updateRoutingTableAndSetTableTimeout(), and updateRoutingTableTimeout().
void PASER_routing_table::updateNeighborFromHELLO (address_list liste, u_int32_t seq, int ifIndex)
Update or add the neighbor entry to IP addresses from a list and update or add the routing to all subnetworks from a list. The entry will be added with the metric equal to 1.
Definition at line 619 of file PASER_routing_table.cc.
References PASER_timer_packet::data, PASER_routing_entry::deleteTimer, PASER_timer_packet::destAddr, PASER_neighbor_table::findNeigh(), PASER_global::getPASERtimeofday(), PASER_timer_packet::handler, PASER_routing_entry::is_gw, PASER_neighbor_entry::neighFlag, PASER_routing_entry::nxthop_addr, PASER_ALLONES_ADDRESS_MASK, PASER_ROUTE_DELETE_TIME, PASER_routing_entry::seqnum, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), update(), updateKernelRoutingTable(), PASER_neighbor_table::updateNeighborTableTimeout(), and PASER_routing_entry::validTimer.
void PASER_routing_table::updateRouteFromHELLO (address_list liste, int ifIndex, struct in_addr nextHop)
Update or add the routing entry to all IP addresses from a list. All entries will be added with the metric equal to 2.
Definition at line 667 of file PASER_routing_table.cc.
References PASER_timer_packet::data, PASER_routing_entry::deleteTimer, PASER_timer_packet::destAddr, PASER_neighbor_table::findNeigh(), PASER_global::getPASERtimeofday(), PASER_timer_packet::handler, PASER_routing_entry::hopcnt, insert(), PASER_routing_entry::is_gw, PASER_neighbor_entry::isValid, PASER_routing_entry::isValid, PASER_neighbor_entry::neighFlag, PASER_routing_entry::nxthop_addr, PASER_ALLONES_ADDRESS_MASK, PASER_ROUTE_DELETE_TIME, PASER_routing_entry::seqnum, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), update(), updateKernelRoutingTable(), and PASER_routing_entry::validTimer.
void PASER_routing_table::updateRouteLifetimes (struct in_addr dest_addr)
Update a valid and delete timer of a route to a given IP address
Definition at line 512 of file PASER_routing_table.cc.
References PASER_timer_packet::data, PASER_neighbor_entry::deleteTimer, PASER_routing_entry::deleteTimer, PASER_timer_packet::destAddr, PASER_neighbor_table::findNeigh(), PASER_global::getPASERtimeofday(), PASER_timer_packet::handler, PASER_neighbor_entry::isValid, PASER_routing_entry::isValid, PASER_neighbor_entry::neighbor_addr, PASER_routing_entry::nxthop_addr, PASER_ROUTE_DELETE_TIME, PASER_neighbor_entry::setValidTimer(), PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), PASER_neighbor_entry::validTimer, and PASER_routing_entry::validTimer.
void PASER_routing_table::updateRoutingTable (struct timeval now, std::list< address_list > addList, struct in_addr nextHop, int ifIndex)
Insert or update a routes to the nodes from a given list.
Parameters:
now Current time
addList A list of a nodes to which a routes will be updated
nextHop IP of the next hop node to the nodes from "addList"
ifIndex Interface over which the nodes are reachable.
Definition at line 391 of file PASER_routing_table.cc.
References PASER_timer_packet::data, PASER_routing_entry::deleteTimer, PASER_timer_packet::destAddr, PASER_neighbor_table::findNeigh(), PASER_timer_packet::handler, PASER_routing_entry::hopcnt, insert(), PASER_routing_entry::is_gw, PASER_neighbor_entry::isValid, PASER_neighbor_entry::neighFlag, PASER_ALLONES_ADDRESS_MASK, PASER_ROUTE_DELETE_TIME, PASER_routing_entry::seqnum, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), update(), updateKernelRoutingTable(), and PASER_routing_entry::validTimer.
void PASER_routing_table::updateRoutingTableAndSetTableTimeout (std::list< address_range > addList, struct in_addr src_addr, uint32_t seq, X509 * cert, struct in_addr nextHop, u_int8_t metric, int ifIndex, struct timeval now, u_int8_t gFlag, bool trusted)
Insert or update a entry in the routing table. If a entry not exist then a new entry will be added to the table. The delete and valid timer of the entry will be reseted.
Parameters:
addList Address range list of the node
src_addr IP address of the node which entry will be updated.
seq Sequence number of the node
cert Certificate of the node
nextHop IP address of the next hop node
metric Metric to the node
ifIndex Interface over which the node is reachable.
now Current time
gFlag Is the node a gateway
trusted Is the Route trusted
Definition at line 246 of file PASER_routing_table.cc.
References PASER_routing_entry::Cert, PASER_timer_packet::data, PASER_routing_entry::deleteTimer, PASER_routing_entry::dest_addr, PASER_timer_packet::destAddr, PASER_neighbor_table::findNeigh(), PASER_timer_packet::handler, PASER_routing_entry::hopcnt, PASER_neighbor_entry::ifIndex, insert(), PASER_routing_entry::is_gw, PASER_routing_entry::isValid, PASER_neighbor_entry::neighFlag, PASER_routing_entry::nxthop_addr, PASER_ALLONES_ADDRESS_MASK, PASER_ROUTE_DELETE_TIME, PASER_routing_entry::seqnum, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), update(), updateKernelRoutingTable(), and PASER_routing_entry::validTimer.
void PASER_routing_table::updateRoutingTableTimeout (struct in_addr src_addr, struct timeval now, int ifIndex)
Reset the delete and valid timer of an entry. If a entry not exist then a new entry will be NOT added.
Definition at line 338 of file PASER_routing_table.cc.
References PASER_timer_packet::data, PASER_routing_entry::deleteTimer, PASER_timer_packet::destAddr, PASER_timer_packet::handler, PASER_routing_entry::isValid, PASER_ALLONES_ADDRESS_MASK, PASER_ROUTE_DELETE_TIME, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), updateKernelRoutingTable(), and PASER_routing_entry::validTimer.
void PASER_routing_table::updateRoutingTableTimeout (struct in_addr src_addr, u_int32_t seq, struct timeval now)
Update the sequence number, delete and valid timer of an entry. If a entry not exist then a new entry will be NOT added.
Definition at line 366 of file PASER_routing_table.cc.
References PASER_timer_packet::data, PASER_routing_entry::deleteTimer, PASER_timer_packet::destAddr, PASER_timer_packet::handler, PASER_routing_entry::isValid, PASER_ROUTE_DELETE_TIME, PASER_routing_entry::seqnum, PASER_timer_packet::timeout, PASER_timer_queue::timer_add(), and PASER_routing_entry::validTimer.
The documentation for this class was generated from the following files:
src/PASER/tables/PASER_routing_table.h
src/PASER/tables/PASER_routing_table.cc