PASER_crypto_sign Class Reference
PASER_crypto_sign Class Reference
Cryptography
Class provides function to compute and check signatures of PASER messages.
#include <PASER_crypto_sign.h>
Public Member Functions
PASER_crypto_sign (char *certPath, char *keyPath, char *CAcertPath, PASER_global *paser_global)
int getCert (lv_block *cert)
X509 * extractCert (lv_block cert)
int signUBRREQ (PASER_UB_RREQ *packet)
int checkSignUBRREQ (PASER_UB_RREQ *packet)
int checkSignKDC (kdc_block data)
int signUURREP (PASER_UU_RREP *packet)
int checkSignUURREP (PASER_UU_RREP *packet)
int signB_ROOT (PASER_B_ROOT *packet)
int checkSignB_ROOT (PASER_B_ROOT *packet)
int checkSignRESET (PASER_RESET *packet)
int checkSignGTKResponse (PASER_GTKREP *packet)
bool isGwCert (X509 *cert)
bool isKdcCert (X509 *cert)
int rsa_encrypt (lv_block in, lv_block *out, X509 *cert)
int rsa_dencrypt (lv_block in, lv_block *out)
int setCRL (lv_block in)
int checkOneCert (X509 *cert)
Detailed Description
Class provides function to compute and check signatures of PASER messages.
Implementation of PASER_crypto_sign classes.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 53 of file PASER_crypto_sign.h.
Constructor & Destructor Documentation
PASER_crypto_sign::PASER_crypto_sign (char * certPath, char * keyPath, char * CAcertPath, PASER_global * paser_global)
Constructor of PASER_crypto_sign Object. Loads own certificate, asymmetric private key and CA certificate.
Parameters:
certPath Path to the own certificate
keyPath Path to the asymmetric private key
CAcertPath Path to the CA certificate
paser_global Pointer to global object
Returns:
nada
Definition at line 53 of file PASER_crypto_sign.cc.
Member Function Documentation
int PASER_crypto_sign::checkOneCert (X509 * cert)
The function checks whether the certificate is valid
Parameters:
cert pointer to the certificate
Returns:
1 on successful or 0 on error
Definition at line 740 of file PASER_crypto_sign.cc.
Referenced by PASER_neighbor_table::checkAllCert(), checkSignB_ROOT(), checkSignGTKResponse(), checkSignKDC(), checkSignRESET(), checkSignUBRREQ(), and checkSignUURREP().
int PASER_crypto_sign::checkSignB_ROOT (PASER_B_ROOT * packet)
Check a signature from PASER_B_ROOT packet
Parameters:
packet pointer to the PASER_B_ROOT packet
Returns:
1 on successful or 0 on error
Definition at line 343 of file PASER_crypto_sign.cc.
References PASER_B_ROOT::cert, checkOneCert(), PASER_B_ROOT::sign, and PASER_B_ROOT::toByteArray().
int PASER_crypto_sign::checkSignGTKResponse (PASER_GTKREP * packet)
Check a signature from PASER_GTKREP packet
Parameters:
packet pointer to the PASER_GTKREP packet
Returns:
1 on successful or 0 on error
Definition at line 436 of file PASER_crypto_sign.cc.
References checkOneCert(), isKdcCert(), PASER_GTKREP::kdc_cert, and PASER_GTKREP::toByteArray().
int PASER_crypto_sign::checkSignKDC (kdc_block data)
Check a signature from kdc_block packet
Parameters:
data kdc_block
Returns:
1 on successful or 0 on error
Definition at line 485 of file PASER_crypto_sign.cc.
References checkOneCert(), extractCert(), and isKdcCert().
int PASER_crypto_sign::checkSignRESET (PASER_RESET * packet)
Check a signature from PASER_RESET packet
Parameters:
packet pointer to the PASER_RESET packet
Returns:
1 on successful or 0 on error
Definition at line 387 of file PASER_crypto_sign.cc.
References PASER_RESET::cert, checkOneCert(), isKdcCert(), PASER_RESET::sign, and PASER_RESET::toByteArray().
int PASER_crypto_sign::checkSignUBRREQ (PASER_UB_RREQ * packet)
Check a signature from PASER_UB_RREQ packet
Parameters:
packet pointer to the PASER_TU_RREQ packet
Returns:
1 on successful or 0 on error
Definition at line 194 of file PASER_crypto_sign.cc.
References PASER_UB_RREQ::certForw, checkOneCert(), PASER_UB_RREQ::sign, and PASER_UB_RREQ::toByteArray().
int PASER_crypto_sign::checkSignUURREP (PASER_UU_RREP * packet)
Check a signature from PASER_UU_RREP packet
Parameters:
packet pointer to the PASER_UU_RREP packet
Returns:
1 on successful or 0 on error
Definition at line 269 of file PASER_crypto_sign.cc.
References PASER_UU_RREP::certForw, checkOneCert(), PASER_UU_RREP::sign, and PASER_UU_RREP::toByteArray().
X509 * PASER_crypto_sign::extractCert (lv_block cert)
Convert a X509 certificate from char array (DER format)
Parameters:
cert lv_block which contains certificate as char array
Returns:
certificate on successful or NULL on error
Definition at line 634 of file PASER_crypto_sign.cc.
Referenced by checkSignKDC().
int PASER_crypto_sign::getCert (lv_block * cert)
Get own certificate as char array (DER format)
Parameters:
cert pointer to the lv_block which will be written
Returns:
1 on successful or 0 on error
Definition at line 126 of file PASER_crypto_sign.cc.
Referenced by PASER_packet_sender::forward_ub_rreq(), and PASER_packet_sender::send_ub_rreq().
bool PASER_crypto_sign::isGwCert (X509 * cert)
Check if the certificate a Gateway's certificate is
Parameters:
cert pointer to the certificate
Returns:
true on successful or false on error
Definition at line 654 of file PASER_crypto_sign.cc.
bool PASER_crypto_sign::isKdcCert (X509 * cert)
Check if the certificate a KDC's certificate is
Parameters:
cert pointer to the certificate
Returns:
true on successful or false on error
Definition at line 674 of file PASER_crypto_sign.cc.
Referenced by checkSignGTKResponse(), checkSignKDC(), and checkSignRESET().
int PASER_crypto_sign::rsa_dencrypt (lv_block in, lv_block * out)
Decrypt the char array with a own asymmetric private key
Parameters:
in char array that is to be decrypted
out pointer to char array which will contain decrypted array
Returns:
1 on successful or 0 on error
Definition at line 716 of file PASER_crypto_sign.cc.
int PASER_crypto_sign::rsa_encrypt (lv_block in, lv_block * out, X509 * cert)
Encrypt the char array with a public key of given certificate
Parameters:
in char array that is to be encrypted
out pointer to char array which will contain encrypted array
cert pointer to the certificate
Returns:
1 on successful or 0 on error
Definition at line 693 of file PASER_crypto_sign.cc.
int PASER_crypto_sign::setCRL (lv_block in)
Set Function to set CRL from char array (DER format)
Parameters:
in char array which contains CRL (DER format)
Returns:
1 on successful or 0 on error
Definition at line 145 of file PASER_crypto_sign.cc.
int PASER_crypto_sign::signB_ROOT (PASER_B_ROOT * packet)
Compute a signature from PASER_B_ROOT packet and write the signature to the packet
Parameters:
packet pointer to the PASER_B_ROOT packet
Returns:
1 on successful or 0 on error
Definition at line 314 of file PASER_crypto_sign.cc.
References PASER_sign_len, PASER_B_ROOT::sign, and PASER_B_ROOT::toByteArray().
int PASER_crypto_sign::signUBRREQ (PASER_UB_RREQ * packet)
Compute a signature from PASER_UB_RREQ packet and write the signature to the packet
Parameters:
packet pointer to the PASER_TU_RREQ packet
Returns:
1 on successful or 0 on error
Definition at line 165 of file PASER_crypto_sign.cc.
References PASER_sign_len, PASER_UB_RREQ::sign, and PASER_UB_RREQ::toByteArray().
Referenced by PASER_packet_sender::forward_ub_rreq(), and PASER_packet_sender::send_ub_rreq().
int PASER_crypto_sign::signUURREP (PASER_UU_RREP * packet)
Compute a signature from PASER_UU_RREP packet and write the signature to the packet
Parameters:
packet pointer to the PASER_UU_RREP packet
Returns:
1 on successful or 0 on error
Definition at line 239 of file PASER_crypto_sign.cc.
References PASER_sign_len, PASER_UU_RREP::sign, and PASER_UU_RREP::toByteArray().
The documentation for this class was generated from the following files:
src/PASER/crypto/PASER_crypto_sign.h
src/PASER/crypto/PASER_crypto_sign.cc