KDC_crypto_sign Class Reference
KDC_crypto_sign Class Reference
Key Distribution Center
Class provides functions to handle with GTK messages.
#include <KDCcryptosign.h>
Public Member Functions
void resetGTK ()
Generate a new GTK.
lv_block getRESETSignCopy ()
Get copy of RESET Message's signature.
lv_block getKDCCert ()
Get copy of certificate (DER format)
lv_block getGTK ()
Get GTK.
int getGTKnumber ()
Get GTK number.
lv_block getCRL ()
Get CRL as DER format.
lv_block getsign_key ()
Get signature of RESET message as DER format.
int checkSignRequest (PASER_GTKREQ *packet)
int signResponse (PASER_GTKREP *packet)
PASER_GTKREP * generateGTKReasponse (PASER_GTKREQ *packet)
int rsa_encrypt (lv_block in, lv_block *out, X509 *cert)
X509 * extractCert (lv_block cert)
int checkOneCert (X509 *cert)
Detailed Description
Class provides functions to handle with GTK messages.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 42 of file KDCcryptosign.h.
Member Function Documentation
int KDC_crypto_sign::checkOneCert (X509 * cert)
The function checks whether the certificate is valid
Parameters:
cert pointer to the certificate
Returns:
1 on successful or 0 on error
Definition at line 346 of file KDCcryptosign.cc.
Referenced by checkSignRequest().
int KDC_crypto_sign::checkSignRequest (PASER_GTKREQ * packet)
Check a signature from PASER_GTKREQ packet
Parameters:
packet pointer to the PASER_GTKREQ packet
Returns:
1 on successful or 0 on error
Definition at line 220 of file KDCcryptosign.cc.
References PASER_GTKREQ::cert, and checkOneCert().
X509* KDC_crypto_sign::extractCert (lv_block cert)
Convert a X509 certificate from char array (DER format)
Parameters:
cert lv_block which contains certificate as char array
Returns:
certificate on successful or NULL on error
PASER_GTKREP * KDC_crypto_sign::generateGTKReasponse (PASER_GTKREQ * packet)
Generate PASER_GTKREP packet from PASER_GTKREQ packet.
Warning:
PASER_GTKREQ packet will not be checked for authenticity. To check for authenticity use checkSignRequest function.
Parameters:
packet
Returns:
Definition at line 260 of file KDCcryptosign.cc.
References PASER_GTKREQ::cert, PASER_GTKREP::crl, getRESETSignCopy(), PASER_GTKREP::gtk, PASER_GTKREP::kdc_cert, PASER_GTKREP::kdc_key_nr, PASER_GTKREP::nonce, PASER_GTKREQ::nonce, rsa_encrypt(), PASER_GTKREP::sign_key, signResponse(), and PASER_MSG::srcAddress_var.
int KDC_crypto_sign::rsa_encrypt (lv_block in, lv_block * out, X509 * cert)
Encrypt the char array with a public key of given certificate
Parameters:
in char array that is to be encrypted
out pointer to char array which will contain encrypted array
cert pointer to the certificate
Returns:
1 on successful or 0 on error
Definition at line 300 of file KDCcryptosign.cc.
Referenced by generateGTKReasponse().
int KDC_crypto_sign::signResponse (PASER_GTKREP * packet)
Compute a signature from PASER_GTKREP packet and write the signature to the packet
Parameters:
packet pointer to the PASER_GTKREP packet
Returns:
1 on successful or 0 on error
Definition at line 319 of file KDCcryptosign.cc.
References PASER_sign_len, and PASER_GTKREP::toByteArray().
Referenced by generateGTKReasponse().
The documentation for this class was generated from the following files:
src/KDC/crypto/KDCcryptosign.h
src/KDC/crypto/KDCcryptosign.cc