PASER_timer_queue Class Reference
PASER_timer_queue Class Reference
Timer Management
Class provides a list of node's timer.
#include <PASER_timer_queue.h>
Public Member Functions
void timer_sort ()
int timer_add (PASER_timer_packet *t)
int timer_remove (PASER_timer_packet *t)
PASER_timer_packet * timer_get_next_timer ()
long timeval_diff (struct timeval *t1, struct timeval *t2)
int getTimerQueueSize ()
Public Attributes
std::list< PASER_timer_packet * > timer_queue
Detailed Description
Class provides a list of node's timer.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 33 of file PASER_timer_queue.h.
Member Function Documentation
int PASER_timer_queue::getTimerQueueSize () [inline]
Get size of timer list
Definition at line 78 of file PASER_timer_queue.h.
References timer_queue.
int PASER_timer_queue::timer_add (PASER_timer_packet * t)
Add a new timer timer to the queue (lower to higher timeout order)
Definition at line 49 of file PASER_timer_queue.cc.
References timer_queue, and timer_remove().
Referenced by PASER_root::getNextSecret(), PASER_route_discovery::route_discovery(), PASER_routing_table::updateNeighborFromHELLO(), PASER_neighbor_table::updateNeighborTableAndSetTableTimeout(), PASER_neighbor_table::updateNeighborTableTimeout(), PASER_routing_table::updateRouteFromHELLO(), PASER_routing_table::updateRouteLifetimes(), PASER_routing_table::updateRoutingTable(), PASER_routing_table::updateRoutingTableAndSetTableTimeout(), and PASER_routing_table::updateRoutingTableTimeout().
PASER_timer_packet * PASER_timer_queue::timer_get_next_timer ()
This Function return next Timeout
Definition at line 109 of file PASER_timer_queue.cc.
References timer_queue.
Referenced by PASER_route_maintenance::handleSelfMsg(), and PASER_scheduler::scheduler().
int PASER_timer_queue::timer_remove (PASER_timer_packet * t)
Remove a timer from the queue
Definition at line 56 of file PASER_timer_queue.cc.
References PASER_timer_packet::destAddr, PASER_timer_packet::handler, PASER_timer_packet::sslFD, and timer_queue.
Referenced by PASER_neighbor_table::checkAllCert(), PASER_routing_table::deleteFromKernelRoutingTableNodesWithNextHopAddr(), and timer_add().
void PASER_timer_queue::timer_sort ()
Sort the list by time
Definition at line 45 of file PASER_timer_queue.cc.
References timer_queue.
Referenced by PASER_root::getNextSecret().
long PASER_timer_queue::timeval_diff (struct timeval * t1, struct timeval * t2)
Get time difference
Parameters:
t1 Pointer to timer
t2 Pointer to timer
Returns:
t1 - t2
Definition at line 116 of file PASER_timer_queue.cc.
Member Data Documentation
std::list<PASER_timer_packet *> PASER_timer_queue::timer_queue
List of node's timer.
Definition at line 38 of file PASER_timer_queue.h.
Referenced by getTimerQueueSize(), PASER_global::resetPASER(), timer_add(), timer_get_next_timer(), timer_remove(), and timer_sort().
The documentation for this class was generated from the following files:
src/PASER/timer_management/PASER_timer_queue.h
src/PASER/timer_management/PASER_timer_queue.cc