PASER_TB_HELLO Class Reference
PASER_TB_HELLO Class Reference
Packet Structure
Class implements PASER_TB_HELLO messages.
#include <PASER_TB_HELLO.h>
Public Member Functions
PASER_TB_HELLO (const PASER_TB_HELLO &m)
PASER_TB_HELLO (struct in_addr src, u_int32_t seqNr)
~PASER_TB_HELLO ()
PASER_TB_HELLO & operator= (const PASER_TB_HELLO &m)
virtual PASER_TB_HELLO * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
std::list< address_list > AddressRangeList
Address range list of sending node.
geo_pos geoQuerying
Geographical position of sending node.
uint8_t * secret
Secret of sending node.
std::list< uint8_t * > auth
Authentication path of sending node.
uint8_t * hash
Hash of the packet.
Detailed Description
Class implements PASER_TB_HELLO messages.
Implementation of PASER_TB_HELLO classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 36 of file PASER_TB_HELLO.h.
Constructor & Destructor Documentation
PASER_TB_HELLO::PASER_TB_HELLO (const PASER_TB_HELLO & m)
Constructor of PASER_TB_HELLO packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 33 of file PASER_TB_HELLO.cc.
References operator=(), and PASER_TB_HELLO().
Referenced by PASER_TB_HELLO().
PASER_TB_HELLO::PASER_TB_HELLO (struct in_addr src, u_int32_t seqNr)
Constructor of PASER_TB_HELLO packet that creates a new packet.
Parameters:
src ip address of sending node
seqNr sequence number of sending node
Definition at line 43 of file PASER_TB_HELLO.cc.
References PASER_MSG::destAddress_var, hash, PASER_TB_HELLO(), secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_TB_HELLO::~PASER_TB_HELLO ()
Destructor
Definition at line 273 of file PASER_TB_HELLO.cc.
References auth, hash, and secret.
Member Function Documentation
std::string PASER_TB_HELLO::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 335 of file PASER_TB_HELLO.cc.
References AddressRangeList, auth, geoQuerying, hash, PASER_SECRET_HASH_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
virtual PASER_TB_HELLO* PASER_TB_HELLO::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 54 of file PASER_TB_HELLO.h.
uint8_t * PASER_TB_HELLO::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 488 of file PASER_TB_HELLO.cc.
References hash, PASER_SECRET_HASH_LEN, and toByteArray().
PASER_TB_HELLO & PASER_TB_HELLO::operator= (const PASER_TB_HELLO & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 294 of file PASER_TB_HELLO.cc.
References AddressRangeList, auth, PASER_MSG::destAddress_var, geoQuerying, hash, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by PASER_TB_HELLO().
uint8_t * PASER_TB_HELLO::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 392 of file PASER_TB_HELLO.cc.
References AddressRangeList, auth, geoQuerying, PASER_SECRET_LEN, secret, PASER_MSG::seq, and PASER_MSG::srcAddress_var.
Referenced by PASER_crypto_hash::checkHmacHELLO(), PASER_crypto_hash::computeHmacHELLO(), and getCompleteByteArray().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_TB_HELLO.h
src/PASER/packet_structure/PASER_TB_HELLO.cc