PASER_RESET Class Reference
PASER_RESET Class Reference
Packet Structure
Class implements PASER_RESET messages.
#include <PASER_RESET.h>
Public Member Functions
PASER_RESET (const PASER_RESET &m)
PASER_RESET (struct in_addr src)
~PASER_RESET ()
PASER_RESET & operator= (const PASER_RESET &m)
virtual PASER_RESET * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
u_int32_t keyNr
Current number of GTK.
lv_block cert
Certificate of KDC.
lv_block sign
Signature of the packet.
Detailed Description
Class implements PASER_RESET messages.
Implementation of PASER_RESET classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 37 of file PASER_RESET.h.
Constructor & Destructor Documentation
PASER_RESET::PASER_RESET (const PASER_RESET & m)
Constructor of PASER_RESET packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 33 of file PASER_RESET.cc.
References operator=(), and PASER_RESET().
Referenced by PASER_RESET().
PASER_RESET::PASER_RESET (struct in_addr src)
Constructor of PASER_RESET packet that creates a new packet.
Parameters:
src ip address of sending node
Definition at line 42 of file PASER_RESET.cc.
References PASER_MSG::destAddress_var, PASER_RESET(), PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_RESET::~PASER_RESET ()
Destructor
Definition at line 162 of file PASER_RESET.cc.
References cert, and sign.
Member Function Documentation
std::string PASER_RESET::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 203 of file PASER_RESET.cc.
References cert, keyNr, sign, PASER_MSG::srcAddress_var, and PASER_MSG::type.
virtual PASER_RESET* PASER_RESET::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 52 of file PASER_RESET.h.
uint8_t * PASER_RESET::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 272 of file PASER_RESET.cc.
References sign, PASER_MSG::srcAddress_var, and toByteArray().
PASER_RESET & PASER_RESET::operator= (const PASER_RESET & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 174 of file PASER_RESET.cc.
References cert, PASER_MSG::destAddress_var, keyNr, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, and PASER_MSG::type.
Referenced by PASER_RESET().
uint8_t * PASER_RESET::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 233 of file PASER_RESET.cc.
References cert, and keyNr.
Referenced by PASER_crypto_sign::checkSignRESET(), and getCompleteByteArray().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_RESET.h
src/PASER/packet_structure/PASER_RESET.cc