PASER_global Class Reference
PASER_global Class Reference
Configuration
Class implements the main functions of PASER.
#include <PASER_global.h>
Public Member Functions
PASER_global (PASER_config *pConfig, PASER_syslog *tmplog)
void resetPASER ()
double getLatPos ()
int getPASERtimeofday (struct timeval *val)
void UpdateTime ()
Detailed Description
Class implements the main functions of PASER.
This class provides pointer to all PASER Modules.
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 51 of file PASER_global.h.
Constructor & Destructor Documentation
PASER_global::PASER_global (PASER_config * pConfig, PASER_syslog * tmplog)
Constructor which should initialize all other modules
Definition at line 25 of file PASER_global.cc.
References PASER_root::init(), PASER_packet_processing::init(), PASER_root_param, GPSDATA::PASER_GPS::startGPS(), and UpdateTime().
Member Function Documentation
double PASER_global::getLatPos ()
get geo position
Definition at line 263 of file PASER_global.cc.
References GPSDATA::PASER_GPS::getLatitude().
int PASER_global::getPASERtimeofday (struct timeval * val)
Get Time when an event has occurred
Definition at line 353 of file PASER_global.cc.
Referenced by PASER_packet_sender::forward_ub_rreq(), PASER_root::getNextSecret(), PASER_route_maintenance::handleSelfMsg(), PASER_route_maintenance::packetFailed(), PASER_route_discovery::processPacket(), PASER_route_discovery::route_discovery(), PASER_scheduler::scheduler(), PASER_packet_sender::send_ub_rreq(), PASER_routing_table::updateNeighborFromHELLO(), PASER_routing_table::updateRouteFromHELLO(), and PASER_routing_table::updateRouteLifetimes().
void PASER_global::resetPASER ()
RESET all PASER Configuration and delete all PASER Tables
Definition at line 294 of file PASER_global.cc.
References PASER_blacklist::clearRerrList(), PASER_rreq_list::clearTable(), PASER_neighbor_table::clearTable(), PASER_routing_table::clearTable(), and PASER_timer_queue::timer_queue.
void PASER_global::UpdateTime ()
Update Time. Should be called one time per event.
Definition at line 362 of file PASER_global.cc.
Referenced by PASER_global(), and PASER_scheduler::scheduler().
The documentation for this class was generated from the following files:
src/PASER/config/PASER_global.h
src/PASER/config/PASER_global.cc