PASER_packet_sender Class Reference
PASER_packet_sender Class Reference
Packet Processing
Class provides functions for working with all PASER messages (sender)
#include <PASER_packet_sender.h>
Public Member Functions
PASER_UB_RREQ * send_ub_rreq (struct in_addr src_addr, struct in_addr dest_addr, int isDestGW)
void sendKDCRequest (struct in_addr nodeAddr, struct in_addr nextHop, lv_block cert, int nonce)
PASER_UB_RREQ * forward_ub_rreq (PASER_UB_RREQ *oldPacket)
Detailed Description
Class provides functions for working with all PASER messages (sender)
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 50 of file PASER_packet_sender.h.
Member Function Documentation
PASER_UB_RREQ * PASER_packet_sender::forward_ub_rreq (PASER_UB_RREQ * oldPacket)
Functions to forward a PASER packets.
Definition at line 533 of file PASER_packet_sender.cc.
References PASER_UB_RREQ::AddressRangeList, PASER_UB_RREQ::certForw, PASER_UB_RREQ::detailedInfo(), PASER_UB_RREQ::geoForwarding, PASER_config::getAddL(), PASER_crypto_sign::getCert(), PASER_UB_RREQ::getCompleteByteArray(), PASER_root::getIV(), PASER_global::getPASERtimeofday(), PASER_root::getRoot(), PASER_UB_RREQ::initVector, PASER_UB_RREQ::metricBetweenQueryingAndForw, PASER_PORT, PASER_UB_RREQ::root, PASER_socket::sendUDPToIPOverNetwork(), PASER_UB_RREQ::seqForw, PASER_crypto_sign::signUBRREQ(), and PASER_UB_RREQ::timestamp.
PASER_UB_RREQ * PASER_packet_sender::send_ub_rreq (struct in_addr src_addr, struct in_addr dest_addr, int isDestGW)
Functions to create, secure and send a PASER packets.
Returns:
pointer to created packet
Definition at line 49 of file PASER_packet_sender.cc.
References PASER_UB_RREQ::AddressRangeList, PASER_UB_RREQ::cert, PASER_UB_RREQ::certForw, PASER_UB_RREQ::detailedInfo(), PASER_UB_RREQ::geoForwarding, PASER_UB_RREQ::geoQuerying, PASER_config::getAddL(), PASER_crypto_sign::getCert(), PASER_UB_RREQ::getCompleteByteArray(), PASER_root::getIV(), PASER_global::getPASERtimeofday(), PASER_root::getRoot(), PASER_UB_RREQ::GFlag, PASER_UB_RREQ::initVector, PASER_UB_RREQ::keyNr, PASER_UB_RREQ::metricBetweenQueryingAndForw, PASER_UB_RREQ::nonce, PASER_BROADCAST, PASER_PORT, PASER_UB_RREQ::root, PASER_UB_RREQ::searchGW, PASER_socket::sendUDPToIPOverNetwork(), PASER_UB_RREQ::seqForw, PASER_crypto_sign::signUBRREQ(), and PASER_UB_RREQ::timestamp.
Referenced by PASER_route_discovery::route_discovery().
void PASER_packet_sender::sendKDCRequest (struct in_addr nodeAddr, struct in_addr nextHop, lv_block cert, int nonce)
Send KDC registration request. The request will be sent over Ethernet. The function can be called only by a gateway.
Parameters:
nodeAddr IP address of the registered node
nextHop IP address of the next hop node to the registered node
cert certificate of the registered node
nonce nonce of the registered node
Definition at line 1024 of file PASER_packet_sender.cc.
References PASER_GTKREQ::cert, PASER_GTKREQ::detailedInfo(), PASER_GTKREQ::getCompleteByteArray(), PASER_GTKREQ::nonce, PASER_PORT_KDC, PASER_socket::sendUDPToIPOverSSL(), and PASER_MSG::srcAddress_var.
The documentation for this class was generated from the following files:
src/PASER/packet_processing/PASER_packet_sender.h
src/PASER/packet_processing/PASER_packet_sender.cc