PASER_UU_RREP Class Reference
PASER_UU_RREP Class Reference
Packet Structure
Class implements PASER_UU_RREP messages.
#include <PASER_UU_RREP.h>
Public Member Functions
PASER_UU_RREP (const PASER_UU_RREP &m)
PASER_UU_RREP (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
~PASER_UU_RREP ()
PASER_UU_RREP & operator= (const PASER_UU_RREP &m)
virtual PASER_UU_RREP * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
u_int32_t keyNr
Current number of GTK.
uint8_t searchGW
search for the gateway
uint8_t GFlag
Gateway flag.
std::list< address_list > AddressRangeList
Route list from querying node to forwarding node.
uint8_t metricBetweenQueryingAndForw
Metric for the route between querying node and forwarding node.
uint8_t metricBetweenDestAndForw
Metric for the route between destination node and forwarding node.
lv_block certForw
Certificate of forwarding node.
uint8_t * root
Root element of forwarding node.
u_int32_t initVector
IV of forwarding node.
geo_pos geoDestination
Geographical position of destination node.
geo_pos geoForwarding
Geographical position of forwarding node.
kdc_block kdc_data
KDC Block.
lv_block sign
Signature of the packet.
long timestamp
Sending or Forwarding time.
Detailed Description
Class implements PASER_UU_RREP messages.
Implementation of PASER_UU_RREP classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 33 of file PASER_UU_RREP.h.
Constructor & Destructor Documentation
PASER_UU_RREP::PASER_UU_RREP (const PASER_UU_RREP & m)
Constructor of PASER_UU_RREP packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 32 of file PASER_UU_RREP.cc.
References operator=(), and PASER_UU_RREP().
Referenced by PASER_UU_RREP().
PASER_UU_RREP::PASER_UU_RREP (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
Constructor of PASER_UU_RREP packet that creates a new packet.
Parameters:
src ip address of sending node
dest ip address of querying node
seqNr sequence number of sending node
Definition at line 43 of file PASER_UU_RREP.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_UU_RREP(), searchGW, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_UU_RREP::~PASER_UU_RREP ()
Destructor
Definition at line 66 of file PASER_UU_RREP.cc.
References certForw, GFlag, kdc_data, root, and sign.
Member Function Documentation
std::string PASER_UU_RREP::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 737 of file PASER_UU_RREP.cc.
References AddressRangeList, certForw, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, initVector, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, PASER_SECRET_HASH_LEN, root, searchGW, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
virtual PASER_UU_RREP* PASER_UU_RREP::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 61 of file PASER_UU_RREP.h.
uint8_t * PASER_UU_RREP::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 1024 of file PASER_UU_RREP.cc.
References sign, and toByteArray().
PASER_UU_RREP & PASER_UU_RREP::operator= (const PASER_UU_RREP & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 655 of file PASER_UU_RREP.cc.
References AddressRangeList, certForw, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, initVector, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, root, searchGW, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
Referenced by PASER_UU_RREP().
uint8_t * PASER_UU_RREP::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 845 of file PASER_UU_RREP.cc.
References AddressRangeList, certForw, PASER_MSG::destAddress_var, geoDestination, geoForwarding, GFlag, initVector, kdc_data, keyNr, metricBetweenDestAndForw, metricBetweenQueryingAndForw, root, searchGW, PASER_MSG::seq, PASER_MSG::srcAddress_var, and timestamp.
Referenced by PASER_crypto_sign::checkSignUURREP(), getCompleteByteArray(), and PASER_crypto_sign::signUURREP().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_UU_RREP.h
src/PASER/packet_structure/PASER_UU_RREP.cc