PASER_TB_RERR Class Reference
PASER_TB_RERR Class Reference
Packet Structure
Class implements PASER_TB_RERR messages.
#include <PASER_TB_RERR.h>
Public Member Functions
PASER_TB_RERR (const PASER_TB_RERR &m)
PASER_TB_RERR (struct in_addr src, u_int32_t seqNr)
~PASER_TB_RERR ()
PASER_TB_RERR & operator= (const PASER_TB_RERR &m)
virtual PASER_TB_RERR * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
u_int32_t keyNr
Current number of GTK.
std::list< unreachableBlock > UnreachableAdressesList
List of unreachable addresses.
geo_pos geoForwarding
Geographical position of forwarding node.
uint8_t * secret
Secret of forwarding node.
std::list< uint8_t * > auth
Authentication path of forwarding node.
uint8_t * hash
Hash of the packet.
Detailed Description
Class implements PASER_TB_RERR messages.
Implementation of PASER_TB_RERR classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http:///</www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 36 of file PASER_TB_RERR.h.
Constructor & Destructor Documentation
PASER_TB_RERR::PASER_TB_RERR (const PASER_TB_RERR & m)
Constructor of PASER_TB_RERR packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 34 of file PASER_TB_RERR.cc.
References operator=(), and PASER_TB_RERR().
Referenced by PASER_TB_RERR().
PASER_TB_RERR::PASER_TB_RERR (struct in_addr src, u_int32_t seqNr)
Constructor of PASER_TB_RERR packet that creates a new packet.
Parameters:
src ip address of sending node
seqNr sequence number of sending node
Definition at line 44 of file PASER_TB_RERR.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_TB_RERR(), PASER_MSG::seq, PASER_MSG::srcAddress_var, and PASER_MSG::type.
PASER_TB_RERR::~PASER_TB_RERR ()
Destructor
Definition at line 252 of file PASER_TB_RERR.cc.
References auth, hash, and secret.
Member Function Documentation
std::string PASER_TB_RERR::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 315 of file PASER_TB_RERR.cc.
References auth, geoForwarding, hash, keyNr, PASER_SECRET_HASH_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, PASER_MSG::type, and UnreachableAdressesList.
virtual PASER_TB_RERR* PASER_TB_RERR::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 56 of file PASER_TB_RERR.h.
uint8_t * PASER_TB_RERR::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 456 of file PASER_TB_RERR.cc.
References hash, PASER_SECRET_HASH_LEN, and toByteArray().
PASER_TB_RERR & PASER_TB_RERR::operator= (const PASER_TB_RERR & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 269 of file PASER_TB_RERR.cc.
References auth, PASER_MSG::destAddress_var, geoForwarding, hash, keyNr, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, PASER_MSG::type, and UnreachableAdressesList.
Referenced by PASER_TB_RERR().
uint8_t * PASER_TB_RERR::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 367 of file PASER_TB_RERR.cc.
References auth, geoForwarding, keyNr, PASER_SECRET_LEN, secret, PASER_MSG::seq, PASER_MSG::srcAddress_var, and UnreachableAdressesList.
Referenced by PASER_crypto_hash::checkHmacRERR(), PASER_crypto_hash::computeHmacRERR(), and getCompleteByteArray().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_TB_RERR.h
src/PASER/packet_structure/PASER_TB_RERR.cc