PASER_UB_RREQ Class Reference
PASER_UB_RREQ Class Reference
Packet Structure
Class implements PASER_UB_RREQ messages.
#include <PASER_UB_RREQ.h>
Public Member Functions
PASER_UB_RREQ (const PASER_UB_RREQ &m)
PASER_UB_RREQ (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
~PASER_UB_RREQ ()
PASER_UB_RREQ & operator= (const PASER_UB_RREQ &m)
virtual PASER_UB_RREQ * dup () const
std::string detailedInfo () const
uint8_t * toByteArray (int *l)
uint8_t * getCompleteByteArray (int *l)
Public Attributes
u_int32_t keyNr
Current number of GTK.
u_int32_t seqForw
Sequence number of forwarding node.
uint8_t searchGW
search for the gateway
uint8_t GFlag
Gateway flag.
std::list< address_list > AddressRangeList
Route list from querying node to forwarding node.
uint8_t metricBetweenQueryingAndForw
Metric for the route between querying node and forwarding node.
lv_block cert
Certificate of sending node.
u_int32_t nonce
Register nonce of sending node.
lv_block certForw
Certificate of forwarding node.
uint8_t * root
Root element of forwarding node.
u_int32_t initVector
IV of forwarding node.
geo_pos geoQuerying
Geographical position of sending node.
geo_pos geoForwarding
Geographical position of forwarding node.
lv_block sign
Signature of the packet.
long timestamp
Sending or forwarding time.
Detailed Description
Class implements PASER_UB_RREQ messages.
Implementation of PASER_UB_RREQ classes
Authors:
Eugen.Paul | Mohamad.Sbeiti @paser.info
Copyright:
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition at line 36 of file PASER_UB_RREQ.h.
Constructor & Destructor Documentation
PASER_UB_RREQ::PASER_UB_RREQ (const PASER_UB_RREQ & m)
Constructor of PASER_UB_RREQ packet that creates an exact copy of another packets.
Parameters:
m the pointer to the packet to copy
Definition at line 32 of file PASER_UB_RREQ.cc.
References operator=(), and PASER_UB_RREQ().
Referenced by PASER_UB_RREQ().
PASER_UB_RREQ::PASER_UB_RREQ (struct in_addr src, struct in_addr dest, u_int32_t seqNr)
Constructor of PASER_UB_RREQ packet that creates a new packet.
Parameters:
src ip address of sending node
dest ip address of querying node
seqNr sequence number of sending node
Definition at line 43 of file PASER_UB_RREQ.cc.
References PASER_MSG::destAddress_var, keyNr, PASER_UB_RREQ(), searchGW, PASER_MSG::seq, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
PASER_UB_RREQ::~PASER_UB_RREQ ()
Destructor
Definition at line 73 of file PASER_UB_RREQ.cc.
References cert, certForw, GFlag, root, and sign.
Member Function Documentation
std::string PASER_UB_RREQ::detailedInfo () const [virtual]
Produces a multi-line description of the packet's contents.
Returns:
description of the packet's contents
Implements PASER_MSG.
Definition at line 566 of file PASER_UB_RREQ.cc.
References AddressRangeList, cert, certForw, PASER_MSG::destAddress_var, geoForwarding, geoQuerying, GFlag, initVector, keyNr, metricBetweenQueryingAndForw, nonce, PASER_SECRET_HASH_LEN, root, searchGW, PASER_MSG::seq, seqForw, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
Referenced by PASER_packet_sender::forward_ub_rreq(), and PASER_packet_sender::send_ub_rreq().
virtual PASER_UB_RREQ* PASER_UB_RREQ::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
Implements PASER_MSG.
Definition at line 67 of file PASER_UB_RREQ.h.
uint8_t * PASER_UB_RREQ::getCompleteByteArray (int * l) [virtual]
Creates and return an array of all fields of the package
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 784 of file PASER_UB_RREQ.cc.
References sign, and toByteArray().
Referenced by PASER_packet_sender::forward_ub_rreq(), and PASER_packet_sender::send_ub_rreq().
PASER_UB_RREQ & PASER_UB_RREQ::operator= (const PASER_UB_RREQ & m)
Function that copy an another packets to myself.
Parameters:
m the pointer to the packet to copy
Returns:
a reference to myself
Definition at line 507 of file PASER_UB_RREQ.cc.
References AddressRangeList, cert, certForw, PASER_MSG::destAddress_var, geoForwarding, geoQuerying, GFlag, initVector, keyNr, metricBetweenQueryingAndForw, nonce, root, searchGW, PASER_MSG::seq, seqForw, sign, PASER_MSG::srcAddress_var, timestamp, and PASER_MSG::type.
Referenced by PASER_UB_RREQ().
uint8_t * PASER_UB_RREQ::toByteArray (int * l) [virtual]
Creates and return an array of all fields that must be secured with hash or signature
Parameters:
l length of created array
Returns:
packet array
Implements PASER_MSG.
Definition at line 638 of file PASER_UB_RREQ.cc.
References AddressRangeList, cert, certForw, PASER_MSG::destAddress_var, geoForwarding, geoQuerying, GFlag, initVector, keyNr, metricBetweenQueryingAndForw, nonce, root, searchGW, PASER_MSG::seq, seqForw, PASER_MSG::srcAddress_var, and timestamp.
Referenced by PASER_crypto_sign::checkSignUBRREQ(), getCompleteByteArray(), and PASER_crypto_sign::signUBRREQ().
The documentation for this class was generated from the following files:
src/PASER/packet_structure/PASER_UB_RREQ.h
src/PASER/packet_structure/PASER_UB_RREQ.cc