nfhook.c File Reference
nfhook.c File Reference
Packet Monitor
Packet Monitor implementation.
#include <linux/netfilter_ipv4.h>
#include <linux/inetdevice.h>
#include <linux/inet.h>
#include <net/route.h>
#include "rom.h"
Functions
static void init_whitelist (void)
Build the whitelist.
unsigned int hook_func (unsigned int hooknum, struct sk_buff *skb, const struct net_device *in, const struct net_device *out, int(*okfn)(struct sk_buff *))
unsigned int hook_func description
int nfhook_init (void)
nfhook_init description
void nfhook_exit (void)
nfhook_exit description
Variables
static struct t_id whitelist [WHITELIST_SIZE+1]
The whitelist contains all IPv4 addresses of this host.
Detailed Description
Packet Monitor implementation.
Authors
Carsten.Vogel | Mohamad.Sbeiti @paser.info
Copyright
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition in file nfhook.c.
Function Documentation
unsigned int hook_func (unsigned int hooknum, struct sk_buff * skb, const struct net_device * in, const struct net_device * out, int(*)(struct sk_buff *) okfn)
unsigned int hook_func description
Parameters
hooknum hooknum
skb skb
in in
out out
sk_buff sk_buff
Returns
NF_ACCEPT
Definition at line 156 of file nfhook.c.
References DEBUG_ROM, ipv4_has_valid_route(), queue_packet_handler(), send_rom_rlife(), and whitelist.
Referenced by nfhook_init().
static void init_whitelist (void) static
Build the whitelist.
We loop through all existing network devices to get their IPv4 and broadcast addresses
Definition at line 44 of file nfhook.c.
References whitelist, and WHITELIST_SIZE.
Referenced by nfhook_init().
Variable Documentation
struct t_id whitelist[WHITELIST_SIZE+1] static
The whitelist contains all IPv4 addresses of this host.
It is used to filter out all packets which are destined for this host as early as possible
Definition at line 37 of file nfhook.c.
Referenced by hook_func(), and init_whitelist().