rom.h File Reference
rom.h File Reference
Properties and definitions of the route-o-matic kernel module.
#include <linux/skbuff.h>
Macros
#define DEBUG_ROM 0
#define WHITELIST_SIZE 32
maximum number of whitelist entries
#define ROUTE_TABLE_SIZE 32
maximum number of route entries
#define QUEUE_SIZE (2 * PAGE_SIZE)
#define LLF_IN_SECONDS 5
Functions
int release_queue_for_dst (struct t_id dst_addr)
release_queue_for_dst will reinject all queued packets for a specific destination and delete the corresponding queue afterwards, if it is not the external queue
void queue_packet_handler (struct sk_buff *skb, int(*okfn)(struct sk_buff *), int ext_dest)
queue_packet_handler is invoked by the route-o-matic netfilter hook for each packet which needs to be queued. It will send out a RREQ message if necessary and enqueue the packet.
int queue_init (void)
queue_init will initialize the queue list with one shared queue for packets for all non-private destinations (identified by 0.0.0.0)
void destroy_queue (void)
destroy_queue will free the allocated memory for ALL q_head structures and the queue FIFO buffers including the shared non-private queue. All buffered packets will be discarded without reinjecting. If you want to reinject them before you have to do this manually using a QREL message. Call this function for a clean termination of route-o-matic.
void dump_queue_list (void)
dump_queue_list dumps the whole buffer to kernel log
int netlink_init (void)
netlink_init
void netlink_exit (void)
netlink_exit
int send_rom_rreq (__be32 dst_addr)
HANDLERS Route Request: broadcast RREQ message to user space.
int send_rom_rlife (__be32 dst_addr)
HANDLERS Route Lifetime: broadcast Route Lifetime(RLIFE) message to user space.
int send_rom_rerr (__be32 dst_addr)
Route Error: broadcast RERR message to user space (LLF)
int nfhook_init (void)
nfhook_init description
void nfhook_exit (void)
nfhook_exit description
int add_route (struct t_id dst_addr)
Adds an IPv4 address to the internal routing table at the table's end.
int delete_route (struct t_id dst_addr)
delete_route deletes a destination from table by overwriting it with the last table entry and set this last entry to zero afterwards
int ipv4_has_valid_route (__be32 dst_addr)
ipv4_has_valid_route returns 1 if the given destination address is listed in the table, otherwise 0.
void dump_route_table (void)
dump_route_table dumps the table to the kernel log
Detailed Description
Properties and definitions of the route-o-matic kernel module.
Authors
Carsten.Vogel | Mohamad.Sbeiti @paser.info
Copyright
(C) 2012 Communication Networks Institute (CNI - Prof. Dr.-Ing. Christian Wietfeld) at Technische Universitaet Dortmund, Germany http://www.kn.e-technik.tu-dortmund.de/
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. For further information see file COPYING in the top level directory
This work is part of the secure wireless mesh networks framework, which is currently under development by CNI
Definition in file rom.h.
Macro Definition Documentation
#define DEBUG_ROM 0
Debugging options:
Set DEBUG_ROM=1 to print out some runtime info to kernel log
Set DEBUG_ROM_VERBOSE=1 to produce a LOT of output for every packet that is processed in the netfilter hook. Caution: this will let the kernel logfile grow HUGE quickly if you got lots of traffic!
All printk() statments will begin with DEBUG_ID
Definition at line 43 of file rom.h.
Referenced by check_and_send_rreq(), create_queue_for_dst(), destroy_queue(), hook_func(), rom_qrel(), rom_rtadd(), and rom_rtdel().
#define LLF_IN_SECONDS 5
Support for Link Layer Feedback (experimental)
Since link layer feedback currently only works with modified WLAN drivers, support is disabled by default. To activate link layer feedback support you have to add the following line:
#define ENABLE_LLF_SUPPORT
Definition at line 76 of file rom.h.
Referenced by send_rom_rerr().
#define QUEUE_SIZE (2 * PAGE_SIZE)
QUEUE_SIZE defines the buffer size in bytes which will be allocated for each queue. Each queued packet needs two pointers stored in this buffer which will be 8 bytes on systems with 32-bit pointers. It is good practice to take a multiple of a PAGE_SIZE here. However this makes its size platform-dependent. For example a common PAGE_SIZE size is 4KB which means you can queue 512 packets. The default here is one PAGE_SIZE
Definition at line 62 of file rom.h.
Referenced by create_queue_for_dst().
Function Documentation
int add_route (struct t_id dest)
Adds an IPv4 address to the internal routing table at the table's end.
Parameters
dest destination address
Returns
-1 or 0
Definition at line 42 of file table.c.
References route_table, and ROUTE_TABLE_SIZE.
Referenced by rom_rtadd().
int delete_route (struct t_id dest)
delete_route deletes a destination from table by overwriting it with the last table entry and set this last entry to zero afterwards
Parameters
dest destination address
Returns
-1 or 0
Definition at line 74 of file table.c.
References route_table, and ROUTE_TABLE_SIZE.
Referenced by rom_rtdel().
int ipv4_has_valid_route (__be32 dst_addr)
ipv4_has_valid_route returns 1 if the given destination address is listed in the table, otherwise 0.
Parameters
dst_addr destination address
Returns
1 or 0
Definition at line 108 of file table.c.
References route_table, and ROUTE_TABLE_SIZE.
Referenced by hook_func().
int netlink_init (void)
netlink_init
Returns
-1 or 0
Definition at line 571 of file netlink.c.
References rom_gnl_family, rom_gnl_ops_qdmp, rom_gnl_ops_qrel, rom_gnl_ops_rtadd, rom_gnl_ops_rtdel, rom_gnl_ops_rtdmp, and rom_gnl_ops_setgw.
Referenced by rom_init().
void queue_packet_handler (struct sk_buff * skb, int(*)(struct sk_buff *) okfn, int ext_dest)
queue_packet_handler is invoked by the route-o-matic netfilter hook for each packet which needs to be queued. It will send out a RREQ message if necessary and enqueue the packet.
Parameters
*skb socket buffer
okfn okfn
ext_dest ext_dest
Returns
void
Definition at line 299 of file queue.c.
References check_and_send_rreq(), and enqueue_packet().
Referenced by hook_func().
int release_queue_for_dst (struct t_id dest)
release_queue_for_dst will reinject all queued packets for a specific destination and delete the corresponding queue afterwards, if it is not the external queue
Parameters
dest destination address
Returns
0 or -EINVAL
Definition at line 126 of file queue.c.
Referenced by rom_qrel(), and rom_rtadd().
int send_rom_rerr (__be32 dst_addr)
Route Error: broadcast RERR message to user space (LLF)
TODO Code nearly identical to above send_rom_rreq() - write a wrapper
Parameters
dst_addr
Returns
...
Definition at line 282 of file netlink.c.
References LLF_IN_SECONDS, ROM_C_RERR, rom_gnl_family, and rom_seqnum.
int send_rom_rlife (__be32 dst_addr)
HANDLERS Route Lifetime: broadcast Route Lifetime(RLIFE) message to user space.
Parameters
dst_addr destination address
Returns
...
Definition at line 194 of file netlink.c.
References ROM_C_RLIFE, rom_gnl_family, and rom_seqnum.
Referenced by hook_func().
int send_rom_rreq (__be32 dst_addr)
HANDLERS Route Request: broadcast RREQ message to user space.
Parameters
dst_addr destination address
Returns
...
Definition at line 137 of file netlink.c.
References ROM_C_RREQ, rom_gnl_family, and rom_seqnum.
Referenced by check_and_send_rreq().